#ifndef __SYSTEM_CONFIGURATION_TYPES_H
#define __SYSTEM_CONFIGURATION_TYPES_H

#include <stdint.h>

typedef enum
{
    SYSTEM_ALIGNMENT_HW_QUAT_6AXIS_KNOWN_YAW = 0,
    SYSTEM_ALIGNMENT_GRAVITY_MAG_TRIAD = 1,
    SYSTEM_ALIGNMENT_HW_QUAT_9AXIS = 2,
    SYSTEM_ALIGNMENT_GRAVITY_KNOWN_YAW = 3
} SystemAlignmentAlgorithm;

typedef enum
{
    SYSTEM_ATTITUDE_SOFTWARE_ALWAYS = 0
} SystemAttitudePolicy;

typedef enum
{
    SYSTEM_MECHANIZATION_CONING2_SCULLING2 = 0
} SystemMechanizationAlgorithm;

typedef enum
{
    SYSTEM_FUSION_NONE = 0,
    SYSTEM_FUSION_KF6
} SystemFusionAlgorithm;

typedef uint32_t SystemDeployTriggerMask;

#define SYSTEM_DEPLOY_TRIGGER_NONE       0UL
#define SYSTEM_DEPLOY_TRIGGER_TILT       (1UL << 0)
#define SYSTEM_DEPLOY_TRIGGER_APOGEE_VZ  (1UL << 1)
#define SYSTEM_DEPLOY_TRIGGER_DELAY      (1UL << 2)
#define SYSTEM_DEPLOY_TRIGGER_MASK_ALL   \
    (SYSTEM_DEPLOY_TRIGGER_TILT | SYSTEM_DEPLOY_TRIGGER_APOGEE_VZ | \
     SYSTEM_DEPLOY_TRIGGER_DELAY)

typedef enum
{
    SYSTEM_TILT_REFERENCE_INITIAL_AXIS = 0,
    SYSTEM_TILT_REFERENCE_NAV_UP
} SystemTiltReference;

typedef enum
{
    SYSTEM_LANDING_MODE_STILLNESS = 0,
    SYSTEM_LANDING_MODE_IMPACT_THEN_STILLNESS,
    SYSTEM_LANDING_MODE_BARO_IMU_WINDOW
} SystemLandingMode;

typedef enum
{
    SYSTEM_BODY_AXIS_X_POSITIVE = 0,
    SYSTEM_BODY_AXIS_X_NEGATIVE,
    SYSTEM_BODY_AXIS_Y_POSITIVE,
    SYSTEM_BODY_AXIS_Y_NEGATIVE,
    SYSTEM_BODY_AXIS_Z_POSITIVE,
    SYSTEM_BODY_AXIS_Z_NEGATIVE
} SystemBodyAxis;

#endif /* __SYSTEM_CONFIGURATION_TYPES_H */
