#ifndef __ADC_POWER_CONFIG_H
#define __ADC_POWER_CONFIG_H

#define ADC_POWER_FULL_SCALE_COUNT     4095U
#define ADC_POWER_NOMINAL_VREF_MV      3300U
#define ADC_POWER_DIVIDER_NUM          2U
#define ADC_POWER_DIVIDER_DEN          1U
#define ADC_POWER_POLL_TIMEOUT_MS      2U
#define ADC_POWER_SAMPLE_PERIOD_US     20000ULL
#define ADC_POWER_DEFAULT_SCALE        2.0f
#define ADC_POWER_DEFAULT_OFFSET_V     0.0f

#endif /* __ADC_POWER_CONFIG_H */
