#ifndef __MISSION_ACTION_OUTPUT_BUILD_CAPABILITIES_H
#define __MISSION_ACTION_OUTPUT_BUILD_CAPABILITIES_H

#define MISSION_ACTION_OUTPUT_BUILD_START_ACTION_AVAILABLE        1U
#define MISSION_ACTION_OUTPUT_BUILD_PARACHUTE_DEPLOY_AVAILABLE    1U

#endif /* __MISSION_ACTION_OUTPUT_BUILD_CAPABILITIES_H */
