#ifndef __JY901B_BAROMETER_BUILD_CAPABILITIES_H
#define __JY901B_BAROMETER_BUILD_CAPABILITIES_H

#define JY901B_BAROMETER_BUILD_DIRECT_ALTITUDE_AVAILABLE          1U
#define JY901B_BAROMETER_BUILD_ALIGNMENT_ORIGIN_QUALIFIED         1U
#define JY901B_BAROMETER_BUILD_LANDING_WINDOW_QUALIFIED           1U

/* Package-owned static estimator recommendation. */
#define JY901B_BAROMETER_BUILD_ESTIMATOR_NOISE_RECOMMENDATION_AVAILABLE 1U
#define JY901B_BAROMETER_RECOMMENDED_ALTITUDE_STD_M               5.0f

#endif /* __JY901B_BAROMETER_BUILD_CAPABILITIES_H */
