#ifndef __JY901B_QUATERNION_BUILD_CAPABILITIES_H
#define __JY901B_QUATERNION_BUILD_CAPABILITIES_H

#define JY901B_QUATERNION_BUILD_OUTPUT_AVAILABLE                  1U
#define JY901B_QUATERNION_BUILD_PREFLIGHT_FALLBACK_QUALIFIED      1U
#define JY901B_QUATERNION_BUILD_PREFLIGHT_ALIGNMENT_6AXIS_QUALIFIED 1U
#define JY901B_QUATERNION_BUILD_PREFLIGHT_ALIGNMENT_9AXIS_QUALIFIED 1U
#define JY901B_QUATERNION_BUILD_AUTHORITATIVE_6AXIS_QUALIFIED     0U
#define JY901B_QUATERNION_BUILD_AUTHORITATIVE_9AXIS_QUALIFIED     0U

#endif /* __JY901B_QUATERNION_BUILD_CAPABILITIES_H */
