from __future__ import annotations

import json
from dataclasses import replace
from pathlib import Path

from silverstar_fccg.app.service import FccgService
from silverstar_fccg.core.workspace import WorkspacePolicy
from silverstar_fccg.generator.assembler import ProjectAssembler
from silverstar_fccg.plugins.catalog import PluginCatalog
from silverstar_fccg.project.model import DeviceInstance, ProjectModel_Load
from silverstar_fccg.project.reference import ReferenceProject_Create


def test_service_normalizes_relative_generation_root(
    tmp_path: Path, workspace_root: Path, monkeypatch
) -> None:
    service = FccgService(workspace_root)
    model = service.ReferenceProject_Create("RelativeRoot")
    monkeypatch.chdir(tmp_path.parent)

    plan = service.GenerationPlan_Create(model, Path(tmp_path.name))

    assert plan.project_root == tmp_path.resolve()
    assert plan.validation.valid


def test_generate_reopen_and_apply_preserves_component_source(
    tmp_path: Path, builtin_catalog
) -> None:
    project_root = tmp_path / "GeneratedReference"
    assembler = ProjectAssembler(WorkspacePolicy(tmp_path), builtin_catalog)
    model = ReferenceProject_Create("GeneratedReference")
    initial_plan = assembler.Plan(model, project_root)
    assert initial_plan.valid and initial_plan.new_project
    result = assembler.Apply(model, initial_plan)
    assert result.files_added > 400

    reopened = ProjectModel_Load(project_root / "SilverStar.ssproject")
    assert reopened.ComponentIds_Get() == model.ComponentIds_Get()
    component_path = project_root / "Devices" / "IMU" / "JY901B" / "Src" / "jy901b_device.c"
    marker = "\n/* PROJECT-OWNED LOCAL ACCEPTANCE CHANGE */\n"
    component_path.write_text(
        component_path.read_text(encoding="utf-8") + marker,
        encoding="utf-8",
        newline="\n",
    )

    reopened.logging_streams = [
        replace(stream, enabled=True, decimation=2)
        if stream.record == "FLIGHT_LOG_RECORD_TELEMETRY_DIAG"
        else stream
        for stream in reopened.logging_streams
    ]
    change_plan = assembler.Plan(reopened, project_root)
    assert change_plan.valid and not change_plan.new_project
    component_operation = next(
        operation
        for operation in change_plan.operations
        if operation.target == "Devices/IMU/JY901B/Src/jy901b_device.c"
    )
    assert component_operation.operation == "PRESERVE"
    modified_targets = {
        operation.target
        for operation in change_plan.operations
        if operation.operation == "MODIFY"
    }
    assert "Generated/Src/project_log_config.c" in modified_targets
    assert not any(target.startswith("Devices/") for target in modified_targets)
    assembler.Apply(reopened, change_plan)
    assert component_path.read_text(encoding="utf-8").endswith(marker)
    assert "FLIGHT_LOG_RECORD_TELEMETRY_DIAG, 1U, 2U" in (
        project_root / "Generated" / "Src" / "project_log_config.c"
    ).read_text(encoding="utf-8")


def test_generated_glue_is_small_static_and_heap_free(tmp_path: Path, builtin_catalog) -> None:
    project_root = tmp_path / "GlueCheck"
    assembler = ProjectAssembler(WorkspacePolicy(tmp_path), builtin_catalog)
    model = ReferenceProject_Create("GlueCheck")
    assembler.Apply(model, assembler.Plan(model, project_root))
    generated_files = sorted(
        path.relative_to(project_root).as_posix()
        for path in (project_root / "Generated").rglob("*")
        if path.is_file()
    )
    assert len(generated_files) == 16
    assert "Generated/Inc/project_storage_binding.h" in generated_files
    assert "Generated/project_semantics.json" in generated_files
    assert "Generated/Inc/project_log_decoder_profile.h" in generated_files
    assert "Generated/Src/project_log_decoder_profile.c" in generated_files
    assert "Generated/Inc/project_capability_routes.h" in generated_files
    assert "Generated/Inc/project_device_instances.h" in generated_files
    assert "Generated/Inc/project_flight_config.h" in generated_files
    assert "Generated/Src/project_capability_routes.c" in generated_files
    assert "Generated/Src/project_device_instances.c" in generated_files
    source_text = "\n".join(
        path.read_text(encoding="utf-8")
        for path in (project_root / "Generated").rglob("*.c")
    )
    assert "AUTO-GENERATED BY SILVERSTAR_FCCG" in source_text
    assert "malloc(" not in source_text
    assert "Register" not in source_text


def test_component_cannot_claim_generated_namespace(
    tmp_path: Path, builtin_catalog
) -> None:
    package = tmp_path / "installed" / "example.protocol.managed_collision" / "1.0.0"
    payload = package / "payload" / "Generated"
    payload.mkdir(parents=True)
    (payload / "component_owned.c").write_text("int collision;\n", encoding="utf-8")
    manifest = {
        "schema_version": 0,
        "id": "example.protocol.managed_collision",
        "name": "Managed Path Collision",
        "type": "device",
        "class": "test",
        "instance_policy": {
            "project_max": 4,
            "same_plugin_multiple": True,
            "multi_instance_ready": True,
        },
        "physical_device": {
            "vendor": "Fixture",
            "model": "Managed Collision",
            "chipset": "Fixture",
            "driver": "Fixture Driver",
        },
        "version": "1.0.0",
        "requires": {"components": [], "resources": [], "capabilities": []},
        "resources": {"provides": []},
        "provides": ["protocol.collision_test"],
        "build": {
            "sources": [],
            "asm_sources": [],
            "include_dirs": [],
            "defines": [],
        },
        "payload": {"roots": ["Generated"]},
        "metadata": {"device_category": "sensor.temperature"},
    }
    (package / "plugin.json").write_text(
        json.dumps(manifest), encoding="utf-8"
    )
    catalog = PluginCatalog(builtin_catalog.builtin_root, tmp_path / "installed")
    catalog.Scan()
    model = ReferenceProject_Create("ManagedCollision")
    model.device_instances.append(
        DeviceInstance("test0", "example.protocol.managed_collision")
    )
    assembler = ProjectAssembler(WorkspacePolicy(tmp_path), catalog)
    plan = assembler.Plan(model, tmp_path / "ManagedCollision")
    assert not plan.valid
    assert any(
        operation.operation == "CONFLICT"
        and operation.target == "Generated/component_owned.c"
        for operation in plan.operations
    )
