from __future__ import annotations

import hashlib
import io
import json
import re
import zipfile
import zlib
from pathlib import Path
from typing import Any

from silverstar_fccg.generator.source_graph import SourceGraph
from silverstar_fccg.generator.hardware_preparation import (
    HardwarePreparationMetadata_Render,
)
from silverstar_fccg.plugins.catalog import PluginCatalog
from silverstar_fccg.project.capabilities import CapabilityResolution_Resolve
from silverstar_fccg.project.model import ProjectModel
from silverstar_fccg.project.logging import (
    LogAvailability_Get,
    ProtocolLogDefinitions_Get,
    ProtocolLogMetadataPath_Get,
)
from silverstar_fccg.project.resources import (
    BoardResourceProvisions_Get,
    ResourceAssignments_Resolve,
)


AUTOGEN_C_COMMENT = "/* AUTO-GENERATED BY SILVERSTAR_FCCG. DO NOT EDIT; THIS FILE MAY BE OVERWRITTEN. */"


def ProjectDigest_Get(model: ProjectModel) -> int:
    data = model.Dictionary_Get()
    data["component_provenance"] = {}
    data["build"]["tool_paths"] = {}
    data["build"]["gcc_path"] = ""
    data["reference_provenance"] = {}
    canonical = json.dumps(data, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return zlib.crc32(canonical.encode("utf-8")) & 0xFFFFFFFF


def ComponentProvenance_Get(catalog: PluginCatalog, component_id: str) -> dict[str, Any]:
    manifest = catalog.Component_Get(component_id)
    digests: dict[str, str] = {}
    aggregate = hashlib.sha256()
    for path in manifest.PayloadFiles_Get():
        relative = path.relative_to(manifest.payload_root).as_posix()
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        digests[relative] = digest
        aggregate.update(relative.encode("utf-8"))
        aggregate.update(b"\0")
        aggregate.update(bytes.fromhex(digest))
    return {
        "version": manifest.version,
        "source": manifest.source,
        "manifest_id": manifest.component_id,
        "payload_digest": aggregate.hexdigest(),
        "files": digests,
    }


def GeneratedFiles_Render(
    model: ProjectModel, catalog: PluginCatalog, graph: SourceGraph
) -> dict[str, bytes]:
    files = {
        "Generated/project_sources.mk": graph.MakeFragment_Render(),
        "Generated/module.mk": _GeneratedModule_Render(),
        "Generated/Inc/project_capability_routes.h": _CapabilityRoutesHeader_Render(),
        "Generated/Inc/project_log_config.h": _LogHeader_Render(),
        "Generated/Inc/project_resources.h": _ResourceHeader_Render(model, catalog),
        "Generated/Src/platform_resources.c": _PlatformResources_Render(model, catalog),
        "Generated/Src/project_capability_routes.c": _CapabilityRoutesSource_Render(
            model, catalog
        ),
        "Generated/Src/project_log_config.c": _LogSource_Render(model),
        "Generated/Src/project_metadata.c": _MetadataSource_Render(model, catalog),
    }
    return {
        name: content if isinstance(content, bytes) else content.encode("utf-8")
        for name, content in files.items()
    }


def MetadataFiles_Render(
    model: ProjectModel, catalog: PluginCatalog, graph: SourceGraph
) -> dict[str, bytes]:
    environment = catalog.Component_Get(model.development_environment)
    if environment.environment is None or environment.environment.renderer != "vscode_eide_gcc":
        raise ValueError("Selected development environment has no trusted renderer")
    model.component_provenance = {
        component_id: ComponentProvenance_Get(catalog, component_id)
        for component_id in model.ComponentIds_Get()
    }
    project_json = json.dumps(
        model.Dictionary_Get(), ensure_ascii=False, indent=2, sort_keys=False
    ) + "\n"
    files = {
        "SilverStar.ssproject": project_json,
        ".fccg/hardware-preparation.json": HardwarePreparationMetadata_Render(
            model, catalog
        ),
        "SilverStar_Configuration.md": _Configuration_Render(model, catalog, graph),
        "Makefile": _Makefile_Render(model),
        f"Targets/{model.build.target_profile}/target.mk": _TargetManifest_Render(
            model, catalog, graph
        ),
        ".vscode/tasks.json": _VsCodeTasks_Render(model),
        ".vscode/settings.json": _VsCodeSettings_Render(),
        ".vscode/extensions.json": _VsCodeExtensions_Render(),
        ".eide/eide.yml": _Eide_Render(model, graph),
        ".eide/files.options.yml": _EideFileOptions_Render(),
        f"{model.identity.name}.code-workspace": _VsCodeWorkspace_Render(model),
        "README.md": _GeneratedReadme_Render(model),
        f"{model.identity.name}.ssdecoder": _DecoderProfile_Render(model, catalog),
    }
    return {
        name: content if isinstance(content, bytes) else content.encode("utf-8")
        for name, content in files.items()
    }


def _GeneratedModule_Render() -> str:
    return f"""# AUTO-GENERATED BY SILVERSTAR_FCCG. DO NOT EDIT.
BUILD_MANIFESTS += Generated/module.mk

C_SOURCES += \\
  Generated/Src/platform_resources.c \\
  Generated/Src/project_capability_routes.c \\
  Generated/Src/project_log_config.c \\
  Generated/Src/project_metadata.c

C_INCLUDES += Generated/Inc
"""


def _CapabilityRoutesHeader_Render() -> str:
    return f"""#ifndef __PROJECT_CAPABILITY_ROUTES_H
#define __PROJECT_CAPABILITY_ROUTES_H

{AUTOGEN_C_COMMENT}

#include <stdint.h>

typedef enum
{{
    PROJECT_CAPABILITY_ROUTE_OK = 0,
    PROJECT_CAPABILITY_ROUTE_INVALID_ARGUMENT,
}} ProjectCapabilityRouteResult;

typedef struct
{{
    uint32_t capability_hash;
    uint32_t provider_instance_hash;
    uint32_t provider_plugin_hash;
    uint32_t consumer_component_hash;
    uint32_t purpose_hash;
    uint8_t automatically_resolved;
}} ProjectCapabilityRoute;

uint16_t ProjectCapabilityRoute_CountGet(void);
ProjectCapabilityRouteResult ProjectCapabilityRoute_Get(
    uint16_t index, ProjectCapabilityRoute *route);

#endif /* __PROJECT_CAPABILITY_ROUTES_H */
"""


def _StringCrc32_Get(value: str) -> int:
    return zlib.crc32(value.encode("utf-8")) & 0xFFFFFFFF


def _CapabilityRoutesSource_Render(
    model: ProjectModel, catalog: PluginCatalog
) -> str:
    resolution = CapabilityResolution_Resolve(model, catalog)
    if not resolution.valid:
        raise ValueError("Cannot generate unresolved capability routes")
    rows = ",\n".join(
        "    {"
        f"0x{_StringCrc32_Get(route.requirement.capability):08X}UL, "
        f"0x{_StringCrc32_Get(route.provider.instance_id):08X}UL, "
        f"0x{_StringCrc32_Get(route.provider.plugin):08X}UL, "
        f"0x{_StringCrc32_Get(route.requirement.consumer_component):08X}UL, "
        f"0x{_StringCrc32_Get(route.requirement.purpose):08X}UL, "
        f"{1 if route.automatic else 0}U}}"
        for route in resolution.routes
    )
    if not rows:
        rows = "    {0UL, 0UL, 0UL, 0UL, 0UL, 1U}"
    return f"""#include "project_capability_routes.h"

{AUTOGEN_C_COMMENT}

#include <stddef.h>

static const ProjectCapabilityRoute s_project_capability_routes[] =
{{
{rows}
}};

uint16_t ProjectCapabilityRoute_CountGet(void)
{{
    return {len(resolution.routes)}U;
}}

ProjectCapabilityRouteResult ProjectCapabilityRoute_Get(
    uint16_t index, ProjectCapabilityRoute *route)
{{
    if ((route == NULL) ||
        (index >= ProjectCapabilityRoute_CountGet()))
    {{
        return PROJECT_CAPABILITY_ROUTE_INVALID_ARGUMENT;
    }}
    *route = s_project_capability_routes[index];
    return PROJECT_CAPABILITY_ROUTE_OK;
}}
"""


def _LogHeader_Render() -> str:
    return f"""#ifndef __PROJECT_LOG_CONFIG_H
#define __PROJECT_LOG_CONFIG_H

{AUTOGEN_C_COMMENT}

#include <stdint.h>

#include "system_log_policy.h"

uint16_t ProjectLogConfig_StreamCountGet(void);
const SystemLogStreamConfig *ProjectLogConfig_StreamByIndexGet(
    uint16_t index);

#endif /* __PROJECT_LOG_CONFIG_H */
"""


def _ResourceHeader_Render(model: ProjectModel, catalog: PluginCatalog) -> str:
    result = ResourceAssignments_Resolve(model, catalog)
    if not result.valid:
        raise ValueError("Cannot generate resource header: " + "; ".join(result.errors))
    includes = set()
    lines: list[str] = []
    for assignment in result.assignments:
        macro = assignment.requirement.binding_macro
        if not macro:
            continue
        header = assignment.provision.metadata.get("header")
        if isinstance(header, str) and header:
            includes.add(header)
        c_id = assignment.provision.metadata.get("c_id", assignment.provision.resource_id)
        lines.append(f"#define {macro:<42} {c_id}")
    include_text = "\n".join(f'#include "{header}"' for header in sorted(includes))
    define_text = "\n".join(lines)
    return f"""#ifndef __PROJECT_RESOURCES_H
#define __PROJECT_RESOURCES_H

{AUTOGEN_C_COMMENT}

{include_text}

{define_text}

#endif /* __PROJECT_RESOURCES_H */
"""


def _PlatformResources_Render(model: ProjectModel, catalog: PluginCatalog) -> str:
    if model.hardware.mode == "custom":
        platform = _CustomPlatformResources_Get(model)
    else:
        board = catalog.Component_Get(model.board)
        platform = _BoardPlatformResources_Get(board)
    uarts = platform.get("uarts", [])
    spis = platform.get("spis", [])
    adcs = platform.get("adcs", [])
    gpios = platform.get("gpios", [])
    uart_values = ",\n".join(
        f"    [{entry.get('c_id', f'PLATFORM_UART_{index + 1}')}] = &{entry['handle']}"
        for index, entry in enumerate(uarts)
    )
    spi_values = ",\n".join(
        f"    [{entry.get('c_id', f'PLATFORM_SPI_{index + 1}')}] = &{entry['handle']}"
        for index, entry in enumerate(spis)
    )
    adc_values = ",\n".join(
        f"    [{entry.get('c_id', f'PLATFORM_ADC_{index + 1}')}] = &{entry['handle']}"
        for index, entry in enumerate(adcs)
    )
    gpio_values = ",\n".join(
        f"    [{entry.get('c_id', f'PLATFORM_GPIO_{index}')}] = "
        f"{{{entry['port']}, {entry['pin']}, "
        f"{int(entry.get('irq_enabled', entry.get('active_high', 0)))}U}}"
        for index, entry in enumerate(gpios)
    )
    return f"""#include "platform_stm32f4_resources.h"

{AUTOGEN_C_COMMENT}

#include <stddef.h>

#include "adc.h"
#include "main.h"
#include "spi.h"
#include "usart.h"

static void * const s_uart_handles[PLATFORM_UART_COUNT] =
{{
{uart_values}
}};

static void * const s_spi_handles[PLATFORM_SPI_COUNT] =
{{
{spi_values}
}};

static void * const s_adc_handles[PLATFORM_ADC_COUNT] =
{{
{adc_values}
}};

static const PlatformStm32f4GpioResource
    s_gpio_resources[PLATFORM_GPIO_COUNT] =
{{
{gpio_values}
}};

void *PlatformStm32f4Resource_UartHandleGet(PlatformUartId id)
{{
    return ((uint32_t)id < (uint32_t)PLATFORM_UART_COUNT) ?
        s_uart_handles[id] : NULL;
}}

void *PlatformStm32f4Resource_SpiHandleGet(PlatformSpiId id)
{{
    return ((uint32_t)id < (uint32_t)PLATFORM_SPI_COUNT) ?
        s_spi_handles[id] : NULL;
}}

void *PlatformStm32f4Resource_AdcHandleGet(PlatformAdcId id)
{{
    return ((uint32_t)id < (uint32_t)PLATFORM_ADC_COUNT) ?
        s_adc_handles[id] : NULL;
}}

uint8_t PlatformStm32f4Resource_GpioGet(
    PlatformGpioId id,
    PlatformStm32f4GpioResource *resource)
{{
    if (((uint32_t)id >= (uint32_t)PLATFORM_GPIO_COUNT) ||
        (resource == NULL))
    {{
        return 0U;
    }}
    *resource = s_gpio_resources[id];
    return 1U;
}}
"""


def _CustomPlatformResources_Get(model: ProjectModel) -> dict[str, list[dict[str, Any]]]:
    platform: dict[str, list[dict[str, Any]]] = {
        "uarts": [],
        "spis": [],
        "adcs": [],
        "gpios": [],
    }
    destinations = {"uart": "uarts", "spi": "spis", "adc": "adcs"}
    for resource in model.hardware.resources:
        metadata = resource.metadata
        destination = destinations.get(resource.kind)
        if destination is not None and isinstance(metadata.get("handle"), str):
            platform[destination].append({"id": resource.resource_id, **metadata})
        elif resource.kind.startswith("gpio_") and isinstance(metadata.get("port"), str):
            platform["gpios"].append({"id": resource.resource_id, **metadata})
    for values in platform.values():
        values.sort(key=lambda entry: int(entry.get("logical_index", 0)))
    return platform


def _BoardPlatformResources_Get(board) -> dict[str, list[dict[str, Any]]]:
    if board.board is not None and not board.board.ioc_file:
        legacy = board.metadata.get("platform_resources")
        if isinstance(legacy, dict):
            return legacy
    platform: dict[str, list[dict[str, Any]]] = {
        "uarts": [],
        "spis": [],
        "adcs": [],
        "gpios": [],
    }
    destinations = {"uart": "uarts", "spi": "spis", "adc": "adcs"}
    for provision in BoardResourceProvisions_Get(board):
        metadata = provision.metadata
        destination = destinations.get(provision.kind)
        if destination is not None and isinstance(metadata.get("handle"), str):
            platform[destination].append(
                {"id": provision.resource_id, **metadata}
            )
        elif provision.kind.startswith("gpio_") and isinstance(
            metadata.get("port"), str
        ):
            platform["gpios"].append(
                {"id": provision.resource_id, **metadata}
            )
    for values in platform.values():
        values.sort(key=lambda entry: str(entry.get("c_id", "")))
    return platform


def _DecoderProfile_Render(model: ProjectModel, catalog: PluginCatalog) -> bytes:
    if len(model.protocol_bundles) != 1:
        raise ValueError("Decoder generation requires exactly one protocol bundle")
    protocol = catalog.Component_Get(model.protocol_bundles[0])
    metadata_path = ProtocolLogMetadataPath_Get(protocol)
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    definitions = ProtocolLogDefinitions_Get(model, catalog)
    capability_resolution = CapabilityResolution_Resolve(model, catalog)
    manifest = {
        "format": "SilverStar.ssdecoder",
        "format_version": 1,
        "project": model.identity.name,
        "firmware_version": model.identity.firmware_version,
        "protocol_component": protocol.component_id,
        "protocol_version": protocol.version,
        "decoder_engine": "SilverStar_FLP generic SSLOG engine",
        "entries": [
            "manifest.json",
            "project_profile.json",
            "sslog_parser_metadata.json",
            "README.md",
        ],
    }
    profile = {
        "project_digest": f"{ProjectDigest_Get(model):08x}",
        "components": list(model.ComponentIds_Get()),
        "devices": [
            {
                "instance_id": instance.instance_id,
                "plugin": instance.plugin,
            }
            for instance in model.device_instances
        ],
        "capability_routes": [
            {
                "capability": route.requirement.capability,
                "purpose": route.requirement.purpose,
                "consumer": route.requirement.consumer_component,
                "provider_instance": route.provider.instance_id,
                "provider_plugin": route.provider.plugin,
                "automatic": route.automatic,
            }
            for route in capability_resolution.routes
        ],
        "enabled_capabilities": {
            instance_id: list(capabilities)
            for instance_id, capabilities in sorted(
                capability_resolution.enabled_by_instance.items()
            )
        },
        "strategies": dict(sorted(model.strategies.items())),
        "modes": {
            slot: list(values) for slot, values in sorted(model.modes.items())
        },
        "available_records": [
            {
                "record": definition.record,
                "level": definition.level.value,
                "available": availability.available,
                "missing": list(availability.missing),
            }
            for definition in definitions
            for availability in (
                LogAvailability_Get(definition, model, catalog),
            )
        ],
        "logging_streams": [
            {
                "record": stream.record,
                "enabled": stream.enabled,
                "policy": stream.policy,
                "decimation": stream.decimation,
                "period_us": stream.period_us,
            }
            for stream in model.logging_streams
        ],
    }
    payloads = {
        "manifest.json": json.dumps(
            manifest, ensure_ascii=False, indent=2, sort_keys=True
        ).encode("utf-8")
        + b"\n",
        "project_profile.json": json.dumps(
            profile, ensure_ascii=False, indent=2, sort_keys=True
        ).encode("utf-8")
        + b"\n",
        "sslog_parser_metadata.json": json.dumps(
            metadata, ensure_ascii=False, indent=2, sort_keys=True
        ).encode("utf-8")
        + b"\n",
        "README.md": (
            "# SilverStar decoder profile\n\n"
            "This archive contains declarative JSON metadata only. SilverStar_FLP "
            "loads it with its generic SSLOG decoder engine; no plugin code is "
            "executed and FCCG does not modify FLP.\n"
        ).encode("utf-8"),
    }
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_STORED) as archive:
        for name in sorted(payloads):
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_STORED
            info.external_attr = 0o100644 << 16
            archive.writestr(info, payloads[name])
    return buffer.getvalue()


def _LogSource_Render(model: ProjectModel) -> str:
    rows = []
    for stream in model.logging_streams:
        rows.append(
            f"    {{{stream.record}, {1 if stream.enabled else 0}U, "
            f"{stream.decimation}U, {stream.period_us}UL,\n"
            f"     SSLOG_STREAM_POLICY_{stream.policy}}}"
        )
    body = ",\n".join(rows)
    return f"""#include "project_log_config.h"

{AUTOGEN_C_COMMENT}

#include <stddef.h>

static const SystemLogStreamConfig s_project_log_streams[] =
{{
{body}
}};

_Static_assert((sizeof(s_project_log_streams) /
                sizeof(s_project_log_streams[0])) == SSLOG_RECORD_COUNT,
               "project log stream count mismatch");

uint16_t ProjectLogConfig_StreamCountGet(void)
{{
    return (uint16_t)(sizeof(s_project_log_streams) /
                      sizeof(s_project_log_streams[0]));
}}

const SystemLogStreamConfig *ProjectLogConfig_StreamByIndexGet(
    uint16_t index)
{{
    return (index < ProjectLogConfig_StreamCountGet()) ?
        &s_project_log_streams[index] : NULL;
}}
"""


def _MetadataSource_Render(model: ProjectModel, catalog: PluginCatalog) -> str:
    device_entries: list[dict[str, Any]] = []
    algorithm_entries: list[dict[str, Any]] = []
    for component_id in model.ComponentIds_Get():
        metadata = catalog.Component_Get(component_id).metadata
        device_entries.extend(metadata.get("device_descriptors", []))
        algorithm_entries.extend(metadata.get("algorithm_descriptors", []))
    device_entries.sort(key=lambda entry: int(entry["order"]))
    algorithm_entries.sort(key=lambda entry: int(entry["order"]))
    device_rows = []
    for descriptor_id, entry in enumerate(device_entries, start=1):
        device_rows.append(
            "    { "
            f"{descriptor_id}U, {entry['class']}, {int(entry.get('instance', 0))}U, "
            f"{int(entry.get('driver_id', 1))}U,\n"
            f"      {entry['flags']},\n"
            f"      {entry['capability']}, {entry['rate']},\n"
            f"      {entry['driver_hash']}, {entry['name_hash']} }}"
        )
    algorithm_rows = []
    for descriptor_id, entry in enumerate(algorithm_entries, start=1):
        algorithm_rows.append(
            "    { "
            f"{descriptor_id}U, {entry['class']}, {int(entry.get('instance', 0))}U,\n"
            f"      (uint16_t){entry['algorithm']},\n"
            f"      {entry['flags']},\n"
            f"      SILVERSTAR_PROJECT_CONFIG_DIGEST ^ 0x{descriptor_id:04X}0000UL, "
            f"{entry['name_hash']} }}"
        )
    digest = ProjectDigest_Get(model)
    return f"""#include "system_descriptor_if.h"

{AUTOGEN_C_COMMENT}

#include <stddef.h>

#include "system_capabilities.h"
#include "system_user_config.h"

#define SILVERSTAR_PROJECT_CONFIG_DIGEST 0x{digest:08X}UL

static const SystemDeviceDescriptor s_device_descriptors[] =
{{
{',\n'.join(device_rows)}
}};

static const SystemAlgorithmDescriptor s_algorithm_descriptors[] =
{{
{',\n'.join(algorithm_rows)}
}};

_Static_assert((sizeof(s_device_descriptors) /
                sizeof(s_device_descriptors[0])) <=
               SYSTEM_DESCRIPTOR_DEVICE_COUNT_MAX,
               "target device descriptor table exceeds interface bound");
_Static_assert((sizeof(s_algorithm_descriptors) /
                sizeof(s_algorithm_descriptors[0])) <=
               SYSTEM_DESCRIPTOR_ALGORITHM_COUNT_MAX,
               "target algorithm descriptor table exceeds interface bound");

uint16_t SystemDescriptor_DeviceCountGet(void)
{{
    return (uint16_t)(sizeof(s_device_descriptors) /
                      sizeof(s_device_descriptors[0]));
}}

SystemDeviceResult SystemDescriptor_DeviceGet(
    uint16_t index, SystemDeviceDescriptor *descriptor)
{{
    if ((descriptor == NULL) ||
        (index >= SystemDescriptor_DeviceCountGet()))
    {{
        return SYSTEM_DEVICE_INVALID_ARGUMENT;
    }}
    *descriptor = s_device_descriptors[index];
    return SYSTEM_DEVICE_OK;
}}

uint16_t SystemDescriptor_AlgorithmCountGet(void)
{{
    return (uint16_t)(sizeof(s_algorithm_descriptors) /
                      sizeof(s_algorithm_descriptors[0]));
}}

SystemDeviceResult SystemDescriptor_AlgorithmGet(
    uint16_t index, SystemAlgorithmDescriptor *descriptor)
{{
    if ((descriptor == NULL) ||
        (index >= SystemDescriptor_AlgorithmCountGet()))
    {{
        return SYSTEM_DEVICE_INVALID_ARGUMENT;
    }}
    *descriptor = s_algorithm_descriptors[index];
    return SYSTEM_DEVICE_OK;
}}

uint32_t SystemDescriptor_ConfigDigestGet(void)
{{
    return SILVERSTAR_PROJECT_CONFIG_DIGEST;
}}
"""


def _Makefile_Render(model: ProjectModel) -> str:
    return f"""########################################################################################################################
# SilverStar authoritative build entry - generated by SilverStar_FCCG
########################################################################################################################

TARGET_PROFILE ?= {model.build.target_profile}
CONFIG ?= Debug

SUPPORTED_TARGETS := {model.build.target_profile}
SUPPORTED_CONFIGS := Debug Release

ifeq ($(filter $(TARGET_PROFILE),$(SUPPORTED_TARGETS)),)
$(error Unsupported TARGET_PROFILE '$(TARGET_PROFILE)'; expected one of: $(SUPPORTED_TARGETS))
endif
ifeq ($(filter $(CONFIG),$(SUPPORTED_CONFIGS)),)
$(error Unsupported CONFIG '$(CONFIG)'; expected one of: $(SUPPORTED_CONFIGS))
endif

TARGET := {model.identity.build_target}
BUILD_ROOT := build/$(TARGET_PROFILE)/$(CONFIG)
ANALYZE ?= 0
ifeq ($(ANALYZE),1)
BUILD_ROOT := build/$(TARGET_PROFILE)/StaticAnalysis/$(CONFIG)
endif

C_SOURCES :=
ASM_SOURCES :=
C_INCLUDES :=
C_DEFS :=
TARGET_FORCED_INCLUDES :=
BUILD_MANIFESTS := Makefile

include Targets/$(TARGET_PROFILE)/target.mk
include Generated/project_sources.mk

FIRST_PARTY_C_SOURCES := $(filter APP/% Algorithm/% Board/% Common/% Devices/% FlightLogic/% Generated/% Interfaces/% Modules/% OS/FreeRTOS/% Platform/% Protocol/% System/% Targets/%,$(C_SOURCES))
THIRD_PARTY_C_SOURCES := $(filter ThirdParty/% Middlewares/Third_Party/%,$(C_SOURCES))
VENDOR_C_SOURCES := $(filter Core/% Drivers/% FATFS/% HardwareGenerated/%,$(C_SOURCES))
CLASSIFIED_C_SOURCES := $(FIRST_PARTY_C_SOURCES) $(THIRD_PARTY_C_SOURCES) $(VENDOR_C_SOURCES)

ifneq ($(words $(C_SOURCES)),$(words $(CLASSIFIED_C_SOURCES)))
$(error The compiler policy does not classify every C source)
endif

ifneq ($(words $(C_SOURCES)),$(words $(sort $(C_SOURCES))))
$(error Duplicate C source detected in authoritative manifests)
endif
ifneq ($(words $(ASM_SOURCES)),$(words $(sort $(ASM_SOURCES))))
$(error Duplicate assembler source detected in authoritative manifests)
endif

ifdef GCC_PATH
CC := "$(GCC_PATH)/$(TOOLCHAIN_PREFIX)gcc"
AS := "$(GCC_PATH)/$(TOOLCHAIN_PREFIX)gcc" -x assembler-with-cpp
CP := "$(GCC_PATH)/$(TOOLCHAIN_PREFIX)objcopy"
SZ := "$(GCC_PATH)/$(TOOLCHAIN_PREFIX)size"
else
CC := $(TOOLCHAIN_PREFIX)gcc
AS := $(TOOLCHAIN_PREFIX)gcc -x assembler-with-cpp
CP := $(TOOLCHAIN_PREFIX)objcopy
SZ := $(TOOLCHAIN_PREFIX)size
endif

HEX := $(CP) -O ihex
BIN := $(CP) -O binary -S
MCU := $(TARGET_MCU_FLAGS)

ifeq ($(CONFIG),Debug)
OPT := -Og
DEBUG_FLAGS := -g3 -gdwarf-2
else ifeq ($(CONFIG),Release)
OPT := -O2
DEBUG_FLAGS := -g
else
$(error CONFIG must be Debug or Release)
endif

FIRST_PARTY_WARNINGS := -Wall -Wextra -Wpedantic -Werror \\
                        -Wconversion -Wsign-conversion -Wshadow -Wundef \\
                        -Wformat=2 -Wdouble-promotion -Wcast-align \\
                        -Wcast-qual -Wstrict-prototypes \\
                        -Wmissing-prototypes -Wswitch-enum -Wvla
ifeq ($(ANALYZE),1)
FIRST_PARTY_WARNINGS += -fanalyzer
endif
VENDOR_WARNINGS := -Wall -Werror=implicit-function-declaration \\
                   -Werror=incompatible-pointer-types -Werror=return-type
THIRD_PARTY_WARNINGS := $(VENDOR_WARNINGS)
SECTION_FLAGS := -fdata-sections -ffunction-sections
INCLUDE_FLAGS := $(addprefix -I,$(C_INCLUDES))
DEFINE_FLAGS := $(addprefix -D,$(C_DEFS))
FORCED_INCLUDE_FLAGS := $(addprefix -include ,$(TARGET_FORCED_INCLUDES))

ASFLAGS := $(MCU) $(INCLUDE_FLAGS) $(OPT) $(DEBUG_FLAGS) -Wall $(SECTION_FLAGS)
CFLAGS := $(MCU) $(DEFINE_FLAGS) $(INCLUDE_FLAGS) $(OPT) $(DEBUG_FLAGS) \\
          $(FORCED_INCLUDE_FLAGS) -std=c11 $(SECTION_FLAGS) -MMD -MP

LDSCRIPT := $(TARGET_LDSCRIPT)
LDFLAGS := $(MCU) $(TARGET_SPECS) -T$(LDSCRIPT) $(TARGET_LIBS) \\
           -Wl,-Map=$(BUILD_ROOT)/$(TARGET).map,--cref -Wl,--gc-sections

C_OBJECTS := $(addprefix $(BUILD_ROOT)/,$(C_SOURCES:.c=.o))
ASM_OBJECTS := $(addprefix $(BUILD_ROOT)/,$(ASM_SOURCES:.s=.o))
FIRST_PARTY_C_OBJECTS := $(addprefix $(BUILD_ROOT)/,$(FIRST_PARTY_C_SOURCES:.c=.o))
THIRD_PARTY_C_OBJECTS := $(addprefix $(BUILD_ROOT)/,$(THIRD_PARTY_C_SOURCES:.c=.o))
VENDOR_C_OBJECTS := $(addprefix $(BUILD_ROOT)/,$(VENDOR_C_SOURCES:.c=.o))
OBJECTS := $(C_OBJECTS) $(ASM_OBJECTS)
DEPENDENCIES := $(C_OBJECTS:.o=.d)

$(FIRST_PARTY_C_OBJECTS): SOURCE_WARNINGS := $(FIRST_PARTY_WARNINGS)
$(THIRD_PARTY_C_OBJECTS): SOURCE_WARNINGS := $(THIRD_PARTY_WARNINGS)
$(VENDOR_C_OBJECTS): SOURCE_WARNINGS := $(VENDOR_WARNINGS)

.PHONY: all clean rebuild list-sources list-build-config host-tests architecture-check power10-check static-analysis artifact-check memory-report

all: $(BUILD_ROOT)/$(TARGET).elf $(BUILD_ROOT)/$(TARGET).hex $(BUILD_ROOT)/$(TARGET).bin

$(BUILD_ROOT)/%.o: %.c $(BUILD_MANIFESTS)
\t@powershell -NoProfile -Command "New-Item -ItemType Directory -Force -Path '$(@D)' | Out-Null"
\t@echo "FCCG_PROGRESS|COMPILE|$<"
\t$(CC) -c $(CFLAGS) $(SOURCE_WARNINGS) -MF"$(@:.o=.d)" -Wa,-a,-ad,-alms=$(BUILD_ROOT)/$*.lst $< -o $@

$(BUILD_ROOT)/%.o: %.s $(BUILD_MANIFESTS)
\t@powershell -NoProfile -Command "New-Item -ItemType Directory -Force -Path '$(@D)' | Out-Null"
\t@echo "FCCG_PROGRESS|COMPILE|$<"
\t$(AS) -c $(ASFLAGS) $< -o $@

$(BUILD_ROOT)/$(TARGET).elf: $(OBJECTS) $(LDSCRIPT)
\t@echo "FCCG_PROGRESS|LINK|$@"
\t$(CC) $(OBJECTS) $(LDFLAGS) -o $@
\t@echo "FCCG_PROGRESS|SIZE|$@"
\t$(SZ) $@

$(BUILD_ROOT)/%.hex: $(BUILD_ROOT)/%.elf
\t@echo "FCCG_PROGRESS|HEX|$@"
\t$(HEX) $< $@

$(BUILD_ROOT)/%.bin: $(BUILD_ROOT)/%.elf
\t@echo "FCCG_PROGRESS|BIN|$@"
\t$(BIN) $< $@

clean:
\tpowershell -NoProfile -Command "if (Test-Path -LiteralPath '$(BUILD_ROOT)') {{ Remove-Item -LiteralPath '$(BUILD_ROOT)' -Recurse -Force }}"

rebuild: clean all

list-sources:
\t@$(foreach source,$(C_SOURCES),echo $(source) & ) echo Assembly: $(ASM_SOURCES)

list-build-config:
\t@$(foreach include,$(C_INCLUDES),echo INCLUDE:$(include) & ) echo CONFIG-INCLUDES-END
\t@$(foreach define,$(C_DEFS),echo DEFINE:$(define) & ) echo CONFIG-DEFINES-END

host-tests:
\tpowershell -NoProfile -ExecutionPolicy Bypass -File Tests/Host/run_tests.ps1

architecture-check:
\tpowershell -NoProfile -ExecutionPolicy Bypass -File Tools/check_architecture.ps1

power10-check:
\tpowershell -NoProfile -ExecutionPolicy Bypass -File Tools/check_power_of_ten.ps1

static-analysis:
\t$(MAKE) TARGET_PROFILE=$(TARGET_PROFILE) CONFIG=$(CONFIG) ANALYZE=1 all

artifact-check: all
\tpowershell -NoProfile -ExecutionPolicy Bypass -File Tools/check_firmware_artifact.ps1 -TargetProfile $(TARGET_PROFILE) -Config $(CONFIG)

memory-report: artifact-check

-include $(DEPENDENCIES)
"""


def _MakeSymbol_Get(value: str) -> str:
    return "_".join(
        part for part in re.split(r"[^A-Za-z0-9]+", value.upper()) if part
    )


def _TargetManifest_Render(
    model: ProjectModel, catalog: PluginCatalog, graph: SourceGraph
) -> str:
    flags = (" \\" + "\n" + "                    ").join(graph.mcu_flags)
    specs = " ".join(graph.specs)
    libraries = " ".join(graph.libraries)
    device_symbols = {
        catalog.Component_Get(instance.plugin).component_class: _MakeSymbol_Get(
            catalog.Component_Get(instance.plugin).name
        )
        for instance in model.device_instances
    }
    platform_backend = _MakeSymbol_Get(
        catalog.Component_Get(model.mcu).component_class
    )
    board_profile = _MakeSymbol_Get(
        catalog.Component_Get(model.board).name
        if model.board
        else (model.hardware.source_label or "CUSTOM_STM32")
    )
    return f"""# AUTO-GENERATED BY SILVERSTAR_FCCG. DO NOT EDIT.
# Target flags are resolved from the selected MCU plugin.
BUILD_MANIFESTS += Targets/{model.build.target_profile}/target.mk

IMU_DRIVER := {device_symbols.get('imu', '')}
GNSS_DRIVER := {device_symbols.get('gnss', '')}
TELEMETRY_DRIVER := {device_symbols.get('telemetry', '')}
PLATFORM_BACKEND := {platform_backend}
BOARD_PROFILE := {board_profile}

TOOLCHAIN_PREFIX ?= {graph.toolchain_prefix}
TARGET_MCU_FLAGS := {flags}
TARGET_LDSCRIPT := {graph.linker_script}
TARGET_SPECS := {specs}
TARGET_LIBS := {libraries}
"""


def _VsCodeTasks_Render(model: ProjectModel) -> str:
    def task(label: str, args: list[str], matcher: Any = "$gcc", group: Any = None) -> dict[str, Any]:
        value: dict[str, Any] = {
            "label": label,
            "type": "shell",
            "command": model.build.tool_paths.get(
                "make", model.build.make_command
            ),
            "args": args,
            "problemMatcher": matcher,
        }
        if group is not None:
            value["group"] = group
        return value

    debug = [f"TARGET_PROFILE={model.build.target_profile}", "CONFIG=Debug"]
    release = [f"TARGET_PROFILE={model.build.target_profile}", "CONFIG=Release"]
    tasks = [
        task(
            "SilverStar: Build Debug",
            [*debug, "all"],
            group={"kind": "build", "isDefault": True},
        ),
        task("SilverStar: Build Release", [*release, "all"]),
        task("SilverStar: Clean Debug", [*debug, "clean"], []),
        task("SilverStar: Clean Release", [*release, "clean"], []),
        task("SilverStar: Host tests", ["host-tests"]),
        task("SilverStar: Architecture check", ["architecture-check"], []),
        task("SilverStar: Power of Ten check", ["power10-check"], []),
        task("SilverStar: Static analysis", [*debug, "static-analysis"]),
        task("SilverStar: Artifact check", [*debug, "artifact-check"]),
    ]
    return json.dumps({"version": "2.0.0", "tasks": tasks}, indent=4) + "\n"


def _VsCodeSettings_Render() -> str:
    settings = {
        "files.encoding": "utf8",
        "files.eol": "\n",
        "C_Cpp.default.cStandard": "c11",
        "C_Cpp.default.compilerPath": "arm-none-eabi-gcc",
    }
    return json.dumps(settings, ensure_ascii=False, indent=4) + "\n"


def _VsCodeExtensions_Render() -> str:
    value = {
        "recommendations": [
            "cl.eide",
            "ms-vscode.cpptools",
            "marus25.cortex-debug",
        ]
    }
    return json.dumps(value, ensure_ascii=False, indent=4) + "\n"


def _VsCodeWorkspace_Render(model: ProjectModel) -> str:
    value = {
        "folders": [{"name": model.identity.name, "path": "."}],
        "settings": {"files.encoding": "utf8", "files.eol": "\n"},
    }
    return json.dumps(value, ensure_ascii=False, indent=4) + "\n"


def _Eide_Render(model: ProjectModel, graph: SourceGraph) -> str:
    defines = "\n".join(f"        - {value}" for value in graph.defines)
    includes = "\n".join(f"        - {value}" for value in graph.include_dirs)
    virtual_set = set(graph.virtual_sources)
    source_dirs = tuple(
        dict.fromkeys(
            str(Path(source).parent).replace("\\", "/")
            for source in graph.sources
            if source not in virtual_set
        )
    )
    source_directories = "\n".join(f"  - {value}" for value in source_dirs)
    virtual_files = "\n".join(
        f"    - path: {value}"
        for value in (*graph.virtual_sources, *graph.asm_sources)
    )
    exclude_block = (
        "    excludeList:\n"
        + "\n".join(f"      - {value}" for value in graph.exclude_sources)
        if graph.exclude_sources
        else "    excludeList: []"
    )
    forced_flags = " ".join(f"-include {value}" for value in graph.forced_includes)
    libraries = " ".join(graph.libraries)

    def target_block(configuration: str, optimization: str) -> str:
        return f"""  {configuration}:
    cppPreprocessAttrs:
      defineList:
{defines}
      incList:
{includes}
      libList: []
{exclude_block}
    settings:
      debugger: cortex-debug
    toolchain: GCC
    toolchainConfigMap:
      GCC:
        archExtensions: ""
        cpuType: Cortex-M4
        floatingPointHardware: single
        options:
          version: 5
          afterBuildTasks: []
          asm-compiler:
            ASM_FLAGS: ""
          beforeBuildTasks: []
          c/cpp-compiler:
            CXX_FLAGS: ""
            C_FLAGS: {forced_flags}
            language-c: c11
            language-cpp: c++11
            one-elf-section-per-data: true
            one-elf-section-per-function: true
            optimization: {optimization}
            warnings: all-warnings
          global:
            $float-abi-type: hard
            arm-thumb-mode: thumb
            not-use-syscalls: true
            output-debug-info: enable
            use-newlib-nano: true
          linker:
            LIB_FLAGS: {libraries}
            output-format: elf
            remove-unused-input-sections: true
            use-float-printf: false
        scatterFilePath: {graph.linker_script}
        storageLayout:
          RAM: []
          ROM: []
        useCustomScatterFile: true"""

    targets = "\n".join(
        (
            target_block("Debug", "level-debug"),
            target_block("Release", "level-2"),
        )
    )
    return f"""# AUTO-GENERATED BY SILVERSTAR_FCCG.
# Native EIDE build graph resolved from the same Project Model as Make and VS Code.
version: "4.1"
name: {json.dumps(model.identity.name, ensure_ascii=False)}
type: ARM
deviceName: STM32F407VE
packDir: null
srcDirs:
{source_directories}
virtualFolder:
  name: <virtual_root>
  files:
{virtual_files}
  folders: []
dependenceList: []
outDir: build\\EIDE\\{model.build.target_profile}
miscInfo:
  uid: silverstar-fccg-{ProjectDigest_Get(model):08x}
targets:
{targets}
"""


def _EideFileOptions_Render() -> str:
    return """# AUTO-GENERATED BY SILVERSTAR_FCCG.
version: "2.1"
options:
  Debug:
    files: {}
    virtualPathFiles: {}
  Release:
    files: {}
    virtualPathFiles: {}
"""


def _Configuration_Render(model: ProjectModel, catalog: PluginCatalog, graph: SourceGraph) -> str:
    lines = [
        f"# {model.identity.name} Configuration",
        "",
        "> AUTO-GENERATED BY SILVERSTAR_FCCG. This human-readable file may be overwritten.",
        "",
        f"- Firmware: `{model.identity.firmware_version}`",
        f"- Build target: `{model.identity.build_target}`",
        f"- Target profile: `{model.build.target_profile}`",
        "- Configurations: `Debug`, `Release`",
        f"- Toolchain prefix: `{graph.toolchain_prefix}`",
        f"- MCU: `{model.mcu}`",
        f"- Board: `{model.board or 'custom hardware'}`",
        f"- Hardware source: `{model.hardware.source_kind}` / `{model.hardware.mode}`",
        f"- Development environment: `{model.development_environment}`",
        f"- Authoritative source graph: `Generated/project_sources.mk`",
        f"- EIDE mode: `{model.build.eide_mode}`",
        "",
        "## Components",
        "",
    ]
    for component_id in model.ComponentIds_Get():
        manifest = catalog.Component_Get(component_id)
        lines.append(
            f"- `{manifest.component_type}` / `{manifest.component_class or 'default'}`: "
            f"{manifest.name} `{manifest.version}` (`{component_id}`)"
        )
    lines.extend(("", "## Strategies", ""))
    for slot, component_id in sorted(model.strategies.items()):
        lines.append(f"- `{slot}`: `{component_id or 'None'}`")
    lines.extend(("", "## Modes", ""))
    for slot, selections in sorted(model.modes.items()):
        lines.append(f"- `{slot}`: `{', '.join(selections) if selections else '[]'}`")
    capability_resolution = CapabilityResolution_Resolve(model, catalog)
    lines.extend(("", "## Enabled Device capabilities", ""))
    for instance in model.device_instances:
        capabilities = capability_resolution.EnabledCapabilitiesForInstance_Get(
            instance.instance_id
        )
        lines.append(
            f"- `{instance.instance_id}`: "
            f"`{', '.join(capabilities) if capabilities else '[]'}`"
        )
    lines.extend(("", "## Resource mapping", ""))
    for key, value in sorted(model.resource_assignments.items()):
        lines.append(f"- `{key}` → `{value}`")
    lines.extend(("", "## SSLOG streams", ""))
    for stream in model.logging_streams:
        state = "enabled" if stream.enabled else "disabled"
        lines.append(
            f"- `{stream.record}`: {state}, `{stream.policy}`, "
            f"decimation={stream.decimation}, period_us={stream.period_us}"
        )
    lines.extend(("", "## Hardware provenance", ""))
    if model.hardware.mode == "custom":
        lines.extend(
            (
                f"- Provider: `{model.hardware.provider}`",
                f"- Imported project: `{model.hardware.source_label}`",
                f"- IOC: `{model.hardware.ioc_file}`",
                f"- Imported MCU: `{model.hardware.mcu}`",
                f"- Snapshot digest: `{model.hardware.source_digest}`",
                "- Verification: custom hardware; not an official SilverStar hardware verification claim",
            )
        )
    else:
        board = catalog.Component_Get(model.board)
        lines.extend(
            (
                f"- Board source kind: `{board.board.source_kind if board.board else 'unknown'}`",
                f"- Verified: `{bool(board.board and board.board.verified)}`",
            )
        )
    lines.extend(("", "## Reference provenance", ""))
    for key, value in sorted(model.reference_provenance.items()):
        lines.append(f"- `{key}`: `{value}`")
    lines.extend(
        (
            "",
            "## Resolved source graph",
            "",
            f"- C sources: `{len(graph.sources)}`",
            f"- Assembler sources: `{len(graph.asm_sources)}`",
            f"- Include directories: `{len(graph.include_dirs)}`",
            f"- Linker script: `{graph.linker_script}`",
        )
    )
    lines.extend(
        (
            "",
            "## Ownership",
            "",
            "Component payloads are project-owned after first copy and are not overwritten by normal Apply.",
            "Only `Generated/` glue and FCCG project/build metadata are normally regenerated by FCCG.",
            "`HardwareGenerated/` is vendor-owned data and is replaced only after an explicit re-import confirmation.",
            "",
        )
    )
    return "\n".join(lines)


def _GeneratedReadme_Render(model: ProjectModel) -> str:
    return f"""# {model.identity.name}

This standalone embedded project was assembled by SilverStar_FCCG from declarative source plugins.
It does not require FCCG or Python to build.

- Debug build: `{model.build.make_command} TARGET_PROFILE={model.build.target_profile} CONFIG=Debug all`
- Release build: `{model.build.make_command} TARGET_PROFILE={model.build.target_profile} CONFIG=Release all`
- Host tests: `{model.build.make_command} host-tests`
- Architecture check: `{model.build.make_command} architecture-check`
- Power of Ten check: `{model.build.make_command} power10-check`
- Static analysis: `{model.build.make_command} static-analysis`
- Artifact check: `{model.build.make_command} TARGET_PROFILE={model.build.target_profile} CONFIG=Debug artifact-check`

Component sources are ordinary project-owned files. FCCG may overwrite `Generated/`,
`SilverStar.ssproject`, `SilverStar_Configuration.md`, and generated editor/build metadata.

Make and native EIDE are rendered from the same resolved source graph. VS Code tasks invoke
the generated standalone project and do not modify global editor settings.
"""
