from __future__ import annotations

from silverstar_fccg.core.errors import FccgError

from dataclasses import dataclass

from silverstar_fccg.plugins.catalog import PluginCatalog
from silverstar_fccg.project.model import ProjectModel


class SourceGraphError(FccgError):
    pass


@dataclass(frozen=True, slots=True)
class SourceGraph:
    sources: tuple[str, ...]
    asm_sources: tuple[str, ...]
    include_dirs: tuple[str, ...]
    defines: tuple[str, ...]
    mcu_flags: tuple[str, ...]
    specs: tuple[str, ...]
    libraries: tuple[str, ...]
    forced_includes: tuple[str, ...]
    virtual_sources: tuple[str, ...]
    exclude_sources: tuple[str, ...]
    linker_script: str
    toolchain_prefix: str

    def MakeFragment_Render(self) -> str:
        lines = [
            "# AUTO-GENERATED BY SILVERSTAR_FCCG. DO NOT EDIT.",
            "# Source of truth: SilverStar.ssproject + installed plugin manifests.",
            "BUILD_MANIFESTS += Generated/project_sources.mk",
            "",
        ]
        lines.extend(_MakeList_Render("C_SOURCES", self.sources))
        lines.extend(_MakeList_Render("ASM_SOURCES", self.asm_sources))
        lines.extend(_MakeList_Render("C_INCLUDES", self.include_dirs))
        lines.extend(_MakeList_Render("C_DEFS", self.defines))
        lines.extend(_MakeList_Render("TARGET_FORCED_INCLUDES", self.forced_includes))
        return "\n".join(lines).rstrip() + "\n"


def _Unique_Ordered(values: list[str]) -> tuple[str, ...]:
    return tuple(dict.fromkeys(values))


def _MakeList_Render(name: str, values: tuple[str, ...]) -> list[str]:
    if not values:
        return [f"{name} +=", ""]
    lines = [f"{name} += \\"]
    for index, value in enumerate(values):
        suffix = " \\" if index < len(values) - 1 else ""
        lines.append(f"  {value}{suffix}")
    lines.append("")
    return lines


def SourceGraph_Resolve(model: ProjectModel, catalog: PluginCatalog) -> SourceGraph:
    sources: list[str] = []
    asm_sources: list[str] = []
    include_dirs: list[str] = []
    defines: list[str] = []
    mcu_flags: list[str] = []
    specs: list[str] = []
    libraries: list[str] = []
    forced_includes: list[str] = []
    virtual_sources: list[str] = []
    exclude_sources: list[str] = []
    linker_scripts: list[str] = []
    toolchain_prefixes: list[str] = []
    selected_protocol_profiles = []
    for component_id in model.ComponentIds_Get():
        manifest = catalog.Component_Get(component_id)
        build = manifest.build
        profile_sources: set[str] = set()
        profile_includes: set[str] = set()
        profile_defines: set[str] = set()
        if manifest.protocol is not None:
            for category, profiles in manifest.protocol.profiles.items():
                selected_id = model.protocol_profiles.get(category)
                for profile in profiles:
                    profile_sources.update(profile.codec_sources)
                    profile_sources.update(profile.parser_sources)
                    profile_includes.update(profile.include_dirs)
                    profile_defines.update(profile.defines)
                    if profile.profile_id == selected_id:
                        selected_protocol_profiles.append((category, profile))
        sources.extend(
            source for source in build.sources if source not in profile_sources
        )
        for slot, variants in build.strategy_sources.items():
            if slot not in model.strategies:
                raise SourceGraphError(
                    f"Build contribution references unknown strategy slot: {slot}"
                )
            state = "selected" if model.strategies[slot] is not None else "none"
            for variant_state, variant_sources in variants.items():
                if variant_state == state:
                    sources.extend(variant_sources)
                else:
                    exclude_sources.extend(variant_sources)
        asm_sources.extend(build.asm_sources)
        include_dirs.extend(
            path for path in build.include_dirs if path not in profile_includes
        )
        defines.extend(
            value for value in build.defines if value not in profile_defines
        )
        mcu_flags.extend(build.mcu_flags)
        specs.extend(build.specs)
        libraries.extend(build.libraries)
        forced_includes.extend(build.forced_includes)
        virtual_sources.extend(build.virtual_sources)
        exclude_sources.extend(build.exclude_sources)
        if build.linker_script:
            linker_scripts.append(build.linker_script)
        if build.toolchain_prefix:
            toolchain_prefixes.append(build.toolchain_prefix)
    selected_profile_ids = {
        (category, profile_id)
        for category, profile_id in model.protocol_profiles.items()
    }
    resolved_profile_ids = {
        (category, profile.profile_id)
        for category, profile in selected_protocol_profiles
    }
    if selected_profile_ids != resolved_profile_ids:
        raise SourceGraphError(
            "Selected protocol profiles are incomplete or ambiguous"
        )
    for _category, profile in selected_protocol_profiles:
        for source in (*profile.codec_sources, *profile.parser_sources):
            if source not in sources:
                sources.append(source)
        for include_dir in profile.include_dirs:
            if include_dir not in include_dirs:
                include_dirs.append(include_dir)
        for define in profile.defines:
            if define not in defines:
                defines.append(define)
    for slot, selected in model.strategies.items():
        if selected is not None:
            continue
        none_defines = {
            component.selection.none_defines
            for component in catalog.SelectionSlot_Get(slot)
            if component.selection is not None and component.selection.none_defines
        }
        if len(none_defines) > 1:
            raise SourceGraphError(
                f"Strategy slot {slot} has inconsistent None build definitions"
            )
        if none_defines:
            defines.extend(next(iter(none_defines)))
    if model.hardware.mode == "custom":
        sources.extend(model.hardware.build_sources)
        asm_sources.extend(model.hardware.asm_sources)
        include_dirs.extend(model.hardware.include_dirs)
        defines.extend(model.hardware.defines)
        if model.hardware.linker_script:
            linker_scripts.append(model.hardware.linker_script)
    generated_sources = (
        "Generated/Src/platform_resources.c",
        "Generated/Src/project_capability_routes.c",
        "Generated/Src/project_device_instances.c",
        "Generated/Src/project_log_decoder_profile.c",
        "Generated/Src/project_log_config.c",
        "Generated/Src/project_metadata.c",
    )
    sources.extend(generated_sources)
    include_dirs.append("Generated/Inc")
    forced_includes.append("Generated/Inc/project_flight_config.h")
    if model.device_instances:
        include_dirs.append("Devices")
    duplicate_sources = sorted(
        source for source in set(sources) if sources.count(source) > 1
    )
    duplicate_asm = sorted(
        source for source in set(asm_sources) if asm_sources.count(source) > 1
    )
    if duplicate_sources or duplicate_asm:
        raise SourceGraphError(
            "Duplicate source contributions: "
            + ", ".join((*duplicate_sources, *duplicate_asm))
        )
    unique_linkers = _Unique_Ordered(linker_scripts)
    if len(unique_linkers) != 1:
        raise SourceGraphError(
            f"Exactly one linker script is required, got {len(unique_linkers)}"
        )
    unique_prefixes = _Unique_Ordered(toolchain_prefixes)
    if len(unique_prefixes) > 1:
        raise SourceGraphError("Selected plugins disagree on the toolchain prefix")
    return SourceGraph(
        sources=tuple(sources),
        asm_sources=tuple(asm_sources),
        include_dirs=_Unique_Ordered(include_dirs),
        defines=_Unique_Ordered(defines),
        mcu_flags=_Unique_Ordered(mcu_flags),
        specs=_Unique_Ordered(specs),
        libraries=_Unique_Ordered(libraries),
        forced_includes=_Unique_Ordered(forced_includes),
        virtual_sources=_Unique_Ordered(virtual_sources),
        exclude_sources=_Unique_Ordered(exclude_sources),
        linker_script=unique_linkers[0],
        toolchain_prefix=unique_prefixes[0] if unique_prefixes else model.build.toolchain_prefix,
    )
