#ifndef __SYSTEM_USER_ALIGNMENT_CONFIG_H
#define __SYSTEM_USER_ALIGNMENT_CONFIG_H

#include "system_alignment.h"
#include "system_configuration_types.h"

/* Build manifests select the one compiled Alignment Strategy. */
#ifndef SYSTEM_ALIGNMENT_BUILD_ALGORITHM
#define SYSTEM_ALIGNMENT_BUILD_ALGORITHM \
    SYSTEM_ALIGNMENT_GRAVITY_KNOWN_YAW
#endif
#define SYSTEM_ALIGNMENT_ALGORITHM SYSTEM_ALIGNMENT_BUILD_ALGORITHM

#ifndef SYSTEM_ALIGNMENT_BUILD_SOURCE
#define SYSTEM_ALIGNMENT_BUILD_SOURCE \
    SYSTEM_ALIGNMENT_ATTITUDE_SOURCE_GRAVITY_KNOWN_YAW
#endif
#ifndef SYSTEM_ALIGNMENT_BUILD_CAPABILITY_IMU
#define SYSTEM_ALIGNMENT_BUILD_CAPABILITY_IMU 1U
#endif
#ifndef SYSTEM_ALIGNMENT_BUILD_CAPABILITY_MAGNETOMETER
#define SYSTEM_ALIGNMENT_BUILD_CAPABILITY_MAGNETOMETER 0U
#endif
#ifndef SYSTEM_ALIGNMENT_BUILD_CAPABILITY_HARDWARE_QUATERNION
#define SYSTEM_ALIGNMENT_BUILD_CAPABILITY_HARDWARE_QUATERNION 0U
#endif
#ifndef SYSTEM_ALIGNMENT_BUILD_GUARD_HARDWARE_QUATERNION
#define SYSTEM_ALIGNMENT_BUILD_GUARD_HARDWARE_QUATERNION 0U
#endif

/* SilverStar ENU yaw: body +X horizontal projection, 0 deg East, +90 North. */
#ifndef SYSTEM_ALIGNMENT_KNOWN_YAW_DEG
#define SYSTEM_ALIGNMENT_KNOWN_YAW_DEG 0.0f
#endif

/* Legacy HW_QUAT_6AXIS_KNOWN_YAW only; deprecated for software alignment. */
#ifndef SYSTEM_ALIGNMENT_KNOWN_YAW_BODY_AXIS
#define SYSTEM_ALIGNMENT_KNOWN_YAW_BODY_AXIS 1
#endif

/* Used only by GRAVITY_MAG_TRIAD; positive is east magnetic declination. */
#ifndef SYSTEM_ALIGNMENT_MAGNETIC_DECLINATION_DEG
#define SYSTEM_ALIGNMENT_MAGNETIC_DECLINATION_DEG 0.0f
#endif

/* Shared non-blocking static window. */
#define SYSTEM_ALIGNMENT_WINDOW_MIN_SAMPLES             100U
#define SYSTEM_ALIGNMENT_WINDOW_MAX_SAMPLES             128U
#define SYSTEM_ALIGNMENT_WINDOW_MIN_DURATION_US       500000ULL
#define SYSTEM_ALIGNMENT_WINDOW_MAX_GAP_US             50000ULL
#define SYSTEM_ALIGNMENT_MAX_GYRO_RADPS                  0.10f
#define SYSTEM_ALIGNMENT_ACCEL_TOLERANCE_MPS2            0.50f
#define SYSTEM_ALIGNMENT_MAX_QUAT_DEVIATION_RAD    0.0872664626f
#define SYSTEM_ALIGNMENT_MAX_TILT_ERROR_RAD        0.0872664626f

/* GRAVITY_MAG_TRIAD quality gates; tune from calibrated field logs. */
#define SYSTEM_ALIGNMENT_MAG_MIN_UT                       10.0f
#define SYSTEM_ALIGNMENT_MAG_MAX_UT                      100.0f
#define SYSTEM_ALIGNMENT_MAG_MAX_MAGNITUDE_DEVIATION_RATIO 0.20f
#define SYSTEM_ALIGNMENT_MAG_DIRECTION_MIN_DOT            0.90f
#define SYSTEM_ALIGNMENT_MAG_HORIZONTAL_MIN_RATIO         0.10f

/* Sources selected for this mission's preflight alignment transaction. */
#ifndef SYSTEM_USER_ALIGNMENT_SELECTED_MASK
#define SYSTEM_USER_ALIGNMENT_SELECTED_MASK \
    (SYSTEM_ALIGNMENT_SOURCE_MASK_ATTITUDE | \
     SYSTEM_ALIGNMENT_SOURCE_MASK_GNSS_ORIGIN | \
     SYSTEM_ALIGNMENT_SOURCE_MASK_BARO_ORIGIN)
#endif

/* Selected sources that must be ready before Alignment can become READY. */
#ifndef SYSTEM_USER_ALIGNMENT_REQUIRED_MASK
#define SYSTEM_USER_ALIGNMENT_REQUIRED_MASK \
    (SYSTEM_ALIGNMENT_SOURCE_MASK_ATTITUDE | \
     SYSTEM_ALIGNMENT_SOURCE_MASK_BARO_ORIGIN)
#endif

/* READY validity guard. All thresholds apply before mission START only. */
#define SYSTEM_USER_ALIGNMENT_GUARD_ENABLE                         1U
#define SYSTEM_USER_ALIGNMENT_GUARD_GYRO_THRESHOLD_RADPS        0.05f
#define SYSTEM_USER_ALIGNMENT_GUARD_ACCEL_TOLERANCE_MPS2        0.50f
#define SYSTEM_USER_ALIGNMENT_GUARD_ATTITUDE_DELTA_RAD     0.034906585f
#define SYSTEM_USER_ALIGNMENT_GUARD_CONFIRM_DURATION_US        100000ULL
#define SYSTEM_USER_ALIGNMENT_GUARD_SAMPLE_FRESHNESS_US        100000ULL

#if ((SYSTEM_USER_ALIGNMENT_REQUIRED_MASK & \
      ~SYSTEM_USER_ALIGNMENT_SELECTED_MASK) != 0U)
#error "Alignment required sources must be a subset of selected sources"
#endif

#if ((SYSTEM_USER_ALIGNMENT_SELECTED_MASK & \
      ~SYSTEM_ALIGNMENT_SOURCE_MASK_DEFINED) != 0U)
#error "Alignment selected mask contains an undefined source"
#endif

#if (SYSTEM_ALIGNMENT_WINDOW_MIN_SAMPLES == 0U) || \
    (SYSTEM_ALIGNMENT_WINDOW_MAX_SAMPLES < \
     SYSTEM_ALIGNMENT_WINDOW_MIN_SAMPLES) || \
    (SYSTEM_ALIGNMENT_WINDOW_MAX_SAMPLES > 128U)
#error "Alignment floating-window sample limits are invalid"
#endif

#endif /* __SYSTEM_USER_ALIGNMENT_CONFIG_H */
