#ifndef __SYSTEM_USER_STARTUP_CONFIG_H
#define __SYSTEM_USER_STARTUP_CONFIG_H

/* Device boot configuration policy. WRITE never performs a pre-read. */
#ifndef SYSTEM_GNSS_BOOT_WRITE_CONFIG
#define SYSTEM_GNSS_BOOT_WRITE_CONFIG       0U
#endif
#ifndef SYSTEM_GNSS_BOOT_VERIFY_CONFIG
#define SYSTEM_GNSS_BOOT_VERIFY_CONFIG      1U
#endif
#ifndef SYSTEM_IMU_BOOT_WRITE_CONFIG
#define SYSTEM_IMU_BOOT_WRITE_CONFIG        1U
#endif
#ifndef SYSTEM_IMU_BOOT_VERIFY_CONFIG
#define SYSTEM_IMU_BOOT_VERIFY_CONFIG       0U
#endif
#ifndef SYSTEM_TELEMETRY_BOOT_WRITE_CONFIG
#define SYSTEM_TELEMETRY_BOOT_WRITE_CONFIG  1U
#endif

/* Body-axis direction of the stationary specific-force vector at startup. */
#define SYSTEM_AXIS_DIRECTION_X_POSITIVE 0U
#define SYSTEM_AXIS_DIRECTION_X_NEGATIVE 1U
#define SYSTEM_AXIS_DIRECTION_Y_POSITIVE 2U
#define SYSTEM_AXIS_DIRECTION_Y_NEGATIVE 3U
#define SYSTEM_AXIS_DIRECTION_Z_POSITIVE 4U
#define SYSTEM_AXIS_DIRECTION_Z_NEGATIVE 5U

#ifndef SYSTEM_IMU_STARTUP_GRAVITY_DIRECTION
#define SYSTEM_IMU_STARTUP_GRAVITY_DIRECTION \
    SYSTEM_AXIS_DIRECTION_Y_POSITIVE
#endif
#define SYSTEM_IMU_GRAVITY_DIRECTION_COS_MIN 0.9396926f

#if (SYSTEM_GNSS_BOOT_WRITE_CONFIG > 1U) || \
    (SYSTEM_GNSS_BOOT_VERIFY_CONFIG > 1U) || \
    (SYSTEM_IMU_BOOT_WRITE_CONFIG > 1U) || \
    (SYSTEM_IMU_BOOT_VERIFY_CONFIG > 1U) || \
    (SYSTEM_TELEMETRY_BOOT_WRITE_CONFIG > 1U)
#error "Startup WRITE/VERIFY switches must be 0 or 1"
#endif

#if (SYSTEM_IMU_STARTUP_GRAVITY_DIRECTION > \
     SYSTEM_AXIS_DIRECTION_Z_NEGATIVE)
#error "Invalid SYSTEM_IMU_STARTUP_GRAVITY_DIRECTION"
#endif

#endif /* __SYSTEM_USER_STARTUP_CONFIG_H */
