#ifndef __SYSTEM_USER_PLATFORM_CAPABILITIES_H
#define __SYSTEM_USER_PLATFORM_CAPABILITIES_H

/* System-owned facilities used by flight-profile compile-time validation. */
#ifndef SYSTEM_BUILD_NAVIGATION_VERTICAL_VELOCITY_AVAILABLE
#define SYSTEM_BUILD_NAVIGATION_VERTICAL_VELOCITY_AVAILABLE       1U
#endif

#ifndef SYSTEM_BUILD_MISSION_MONOTONIC_TIME_AVAILABLE
#define SYSTEM_BUILD_MISSION_MONOTONIC_TIME_AVAILABLE \
    SYSTEM_SELECTED_TIME_MONOTONIC_AVAILABLE
#endif

#endif /* __SYSTEM_USER_PLATFORM_CAPABILITIES_H */
