#ifndef __SILVERSTAR_SENSOR_ID_H
#define __SILVERSTAR_SENSOR_ID_H

typedef enum
{
    SILVERSTAR_SENSOR_ID_INVALID = 0x00U,
    SILVERSTAR_SENSOR_ID_IMU = 0x01U,
    SILVERSTAR_SENSOR_ID_GNSS = 0x02U,
    SILVERSTAR_SENSOR_ID_BAROMETER = 0x03U,
    SILVERSTAR_SENSOR_ID_MAGNETOMETER = 0x04U,
    SILVERSTAR_SENSOR_ID_AIR_DATA = 0x05U,
    SILVERSTAR_SENSOR_ID_RANGEFINDER = 0x06U,
    SILVERSTAR_SENSOR_ID_RADAR_ALTIMETER = 0x07U,
    SILVERSTAR_SENSOR_ID_SUN_SENSOR = 0x08U,
    SILVERSTAR_SENSOR_ID_STAR_TRACKER = 0x09U,
    SILVERSTAR_SENSOR_ID_VISION = 0x0AU,
    SILVERSTAR_SENSOR_ID_EXTERNAL_ATTITUDE = 0x0BU,
    SILVERSTAR_SENSOR_ID_DUAL_GNSS_HEADING = 0x0CU,
    SILVERSTAR_SENSOR_ID_TEMPERATURE = 0x0DU,
    SILVERSTAR_SENSOR_ID_HUMIDITY = 0x0EU
} SilverStarSensorId;

#endif /* __SILVERSTAR_SENSOR_ID_H */
