/* SSLOG record catalogue and wire payload metadata.
 *
 * This is ordinary, version-controlled protocol source.  The JSON schema is
 * retained as parser documentation and is not consumed by the firmware build.
 */
#ifndef __SSLOG_RECORDS_H
#define __SSLOG_RECORDS_H

#include <stdint.h>

typedef enum
{
    FLIGHT_LOG_RECORD_SAMPLE = 0x01U,
    FLIGHT_LOG_RECORD_EVENT = 0x02U,
    FLIGHT_LOG_RECORD_STATS = 0x03U,
    FLIGHT_LOG_RECORD_ESTIMATOR = 0x04U,
    FLIGHT_LOG_RECORD_SYSTEM_CONFIG = 0x05U,
    FLIGHT_LOG_RECORD_RAW_SENSOR = 0x06U,
    FLIGHT_LOG_RECORD_PURE_INS = 0x07U,
    FLIGHT_LOG_RECORD_KF6_DIAGNOSTIC = 0x08U,
    FLIGHT_LOG_RECORD_KF6_FULL_P = 0x09U,
    FLIGHT_LOG_RECORD_POWER = 0x0AU,
    FLIGHT_LOG_RECORD_HEALTH = 0x0BU,
    FLIGHT_LOG_RECORD_TELEMETRY_DIAG = 0x0CU,
    FLIGHT_LOG_RECORD_INITIAL_STATE = 0x0DU,
    FLIGHT_LOG_RECORD_IMU_NATIVE = 0x0EU,
    FLIGHT_LOG_RECORD_GNSS_NATIVE = 0x0FU,
    FLIGHT_LOG_RECORD_BARO_NATIVE = 0x10U,
    FLIGHT_LOG_RECORD_MAG_NATIVE = 0x11U,
    FLIGHT_LOG_RECORD_HW_QUAT_NATIVE = 0x12U,
    FLIGHT_LOG_RECORD_INERTIAL_INCREMENT = 0x13U,
    FLIGHT_LOG_RECORD_GNSS_MEASUREMENT = 0x14U,
    FLIGHT_LOG_RECORD_BARO_MEASUREMENT = 0x15U,
    FLIGHT_LOG_RECORD_IMU_CORRECTED = 0x16U,
    FLIGHT_LOG_RECORD_CALIBRATION_RESULT = 0x17U,
    FLIGHT_LOG_RECORD_ALIGNMENT_RESULT = 0x18U,
    FLIGHT_LOG_RECORD_MISSION_CONFIG = 0x19U,
    FLIGHT_LOG_RECORD_DEVICE_DESCRIPTOR = 0x1AU,
    FLIGHT_LOG_RECORD_ALGORITHM_DESCRIPTOR = 0x1BU,
    FLIGHT_LOG_RECORD_LOG_STREAM_DESCRIPTOR = 0x1CU
} FlightLogRecordType;

typedef enum
{
    SSLOG_STREAM_POLICY_EVERY = 0U,
    SSLOG_STREAM_POLICY_DECIMATION,
    SSLOG_STREAM_POLICY_PERIODIC,
    SSLOG_STREAM_POLICY_EVENT,
    SSLOG_STREAM_POLICY_ONE_SHOT
} SslogStreamPolicy;

typedef struct
{
    FlightLogRecordType record_type;
    uint8_t record_version;
    uint16_t payload_size;
    const char *name;
} SslogRecordMetadata;

#define FLIGHT_LOG_SAMPLE_PAYLOAD_SIZE 196U
#define FLIGHT_LOG_EVENT_PAYLOAD_SIZE  12U
#define FLIGHT_LOG_STATS_PAYLOAD_SIZE  16U
#define FLIGHT_LOG_ESTIMATOR_PAYLOAD_SIZE 136U
#define FLIGHT_LOG_SYSTEM_CONFIG_PAYLOAD_SIZE 132U
#define FLIGHT_LOG_RAW_SENSOR_PAYLOAD_SIZE 132U
#define FLIGHT_LOG_PURE_INS_PAYLOAD_SIZE  68U
#define FLIGHT_LOG_KF6_DIAGNOSTIC_PAYLOAD_SIZE 104U
#define FLIGHT_LOG_KF6_FULL_P_PAYLOAD_SIZE  84U
#define FLIGHT_LOG_POWER_PAYLOAD_SIZE  44U
#define FLIGHT_LOG_HEALTH_PAYLOAD_SIZE  40U
#define FLIGHT_LOG_TELEMETRY_DIAG_PAYLOAD_SIZE  48U
#define FLIGHT_LOG_INITIAL_STATE_PAYLOAD_SIZE 144U
#define FLIGHT_LOG_IMU_NATIVE_PAYLOAD_SIZE  76U
#define FLIGHT_LOG_GNSS_NATIVE_PAYLOAD_SIZE  80U
#define FLIGHT_LOG_BARO_NATIVE_PAYLOAD_SIZE  44U
#define FLIGHT_LOG_MAG_NATIVE_PAYLOAD_SIZE  56U
#define FLIGHT_LOG_HW_QUAT_NATIVE_PAYLOAD_SIZE  44U
#define FLIGHT_LOG_INERTIAL_INCREMENT_PAYLOAD_SIZE  52U
#define FLIGHT_LOG_GNSS_MEASUREMENT_PAYLOAD_SIZE  72U
#define FLIGHT_LOG_BARO_MEASUREMENT_PAYLOAD_SIZE  32U
#define FLIGHT_LOG_IMU_CORRECTED_PAYLOAD_SIZE  60U
#define FLIGHT_LOG_CALIBRATION_RESULT_PAYLOAD_SIZE  72U
#define FLIGHT_LOG_ALIGNMENT_RESULT_PAYLOAD_SIZE  96U
#define FLIGHT_LOG_MISSION_CONFIG_PAYLOAD_SIZE  91U
#define FLIGHT_LOG_DEVICE_DESCRIPTOR_PAYLOAD_SIZE  24U
#define FLIGHT_LOG_ALGORITHM_DESCRIPTOR_PAYLOAD_SIZE  16U
#define FLIGHT_LOG_STREAM_DESCRIPTOR_PAYLOAD_SIZE  12U

#define SSLOG_RECORD_COUNT 28U
#define SSLOG_MAX_PAYLOAD_SIZE 256U

uint16_t SslogRecords_RecordCountGet(void);
const SslogRecordMetadata *SslogRecords_MetadataByIndexGet(
    uint16_t index);
const SslogRecordMetadata *SslogRecords_MetadataGet(
    FlightLogRecordType record_type);

#endif /* __SSLOG_RECORDS_H */
