#ifndef __SYSTEM_VERSION_H
#define __SYSTEM_VERSION_H

#include "system_user_config.h"

#define SILVERSTAR_STRINGIFY_INNER(x) #x
#define SILVERSTAR_STRINGIFY(x) SILVERSTAR_STRINGIFY_INNER(x)
#define SILVERSTAR_VERSION_STRING \
    SILVERSTAR_STRINGIFY(SILVERSTAR_VERSION_MAJOR) "." \
    SILVERSTAR_STRINGIFY(SILVERSTAR_VERSION_MINOR) "." \
    SILVERSTAR_STRINGIFY(SILVERSTAR_VERSION_PATCH)
#define SILVERSTAR_PRODUCT_STRING "SilverStar " SILVERSTAR_VERSION_STRING

#endif /* __SYSTEM_VERSION_H */
