#ifndef __TARGET_BUILD_CAPABILITIES_H
#define __TARGET_BUILD_CAPABILITIES_H

#include "target_system_config.h"

/* Compile-time capabilities selected by Targets/SilverStar_F407/target.mk. */
#define TARGET_COMPILED_SYSTEM_CAPABILITIES \
    ((SYSTEM_USER_IMU_ENABLE * SYSTEM_CAPABILITY_IMU) | \
     (SYSTEM_USER_GNSS_ENABLE * SYSTEM_CAPABILITY_GNSS) | \
     (SYSTEM_USER_MAGNETOMETER_ENABLE * SYSTEM_CAPABILITY_MAGNETOMETER) | \
     (SYSTEM_USER_BAROMETER_ENABLE * SYSTEM_CAPABILITY_BAROMETER) | \
     (SYSTEM_USER_HARDWARE_QUATERNION_ENABLE * \
      SYSTEM_CAPABILITY_HARDWARE_QUATERNION) | \
     (SYSTEM_USER_TELEMETRY_ENABLE * SYSTEM_CAPABILITY_TELEMETRY) | \
     (SYSTEM_USER_CONSOLE_ENABLE * SYSTEM_CAPABILITY_CONSOLE) | \
     (SYSTEM_USER_POWER_ENABLE * SYSTEM_CAPABILITY_POWER) | \
     (SYSTEM_USER_STORAGE_ENABLE * SYSTEM_CAPABILITY_STORAGE) | \
     (SYSTEM_USER_OUTPUT_ENABLE * SYSTEM_CAPABILITY_OUTPUT))

#endif /* __TARGET_BUILD_CAPABILITIES_H */
