#ifndef __TARGET_SYSTEM_CONFIG_H
#define __TARGET_SYSTEM_CONFIG_H

#include "system_capabilities.h"
#include "system_configuration_types.h"
#include "jy901b_barometer_build_capabilities.h"
#include "jy901b_imu_build_capabilities.h"
#include "jy901b_magnetometer_build_capabilities.h"
#include "jy901b_quaternion_build_capabilities.h"
#include "mission_action_output_build_capabilities.h"
#include "neo_m9n_build_capabilities.h"

/*
 * Build-time composition for the SilverStar_F407 target.  Concrete Device
 * Adapters and SS0.5 Board services are selected by target.mk;
 * Generated contains only the reference connection and metadata glue.  There
 * is no runtime device registry.
 */
#ifndef SYSTEM_USER_IMU_ENABLE
#define SYSTEM_USER_IMU_ENABLE                         1U
#endif
#ifndef SYSTEM_USER_GNSS_ENABLE
#define SYSTEM_USER_GNSS_ENABLE                        1U
#endif
#ifndef SYSTEM_USER_MAGNETOMETER_ENABLE
#define SYSTEM_USER_MAGNETOMETER_ENABLE                0U
#endif
#ifndef SYSTEM_USER_BAROMETER_ENABLE
#define SYSTEM_USER_BAROMETER_ENABLE                   1U
#endif
#ifndef SYSTEM_USER_HARDWARE_QUATERNION_ENABLE
#define SYSTEM_USER_HARDWARE_QUATERNION_ENABLE         1U
#endif
#ifndef SYSTEM_USER_TELEMETRY_ENABLE
#define SYSTEM_USER_TELEMETRY_ENABLE                   1U
#endif
#ifndef SYSTEM_USER_CONSOLE_ENABLE
#define SYSTEM_USER_CONSOLE_ENABLE                     1U
#endif
#ifndef SYSTEM_USER_POWER_ENABLE
#define SYSTEM_USER_POWER_ENABLE                       1U
#endif
#ifndef SYSTEM_USER_STORAGE_ENABLE
#define SYSTEM_USER_STORAGE_ENABLE                     1U
#endif
#ifndef SYSTEM_USER_LOG_SINK_ENABLE
#define SYSTEM_USER_LOG_SINK_ENABLE                    1U
#endif
#ifndef SYSTEM_USER_OUTPUT_ENABLE
#define SYSTEM_USER_OUTPUT_ENABLE                      1U
#endif
#ifndef SYSTEM_USER_MISSION_ACTION_ENABLE
#define SYSTEM_USER_MISSION_ACTION_ENABLE              1U
#endif
#ifndef SYSTEM_USER_TIME_SOURCE_ENABLE
#define SYSTEM_USER_TIME_SOURCE_ENABLE                 1U
#endif

#ifndef SYSTEM_PROFILE_REQUIRED_CAPABILITIES
#define SYSTEM_PROFILE_REQUIRED_CAPABILITIES \
    (SYSTEM_CAPABILITY_IMU | SYSTEM_CAPABILITY_OUTPUT)
#endif
#ifndef SYSTEM_PROFILE_OPTIONAL_CAPABILITIES
#define SYSTEM_PROFILE_OPTIONAL_CAPABILITIES \
    (SYSTEM_CAPABILITY_GNSS | SYSTEM_CAPABILITY_MAGNETOMETER | \
     SYSTEM_CAPABILITY_BAROMETER | SYSTEM_CAPABILITY_HARDWARE_QUATERNION | \
     SYSTEM_CAPABILITY_TELEMETRY | SYSTEM_CAPABILITY_CONSOLE | \
     SYSTEM_CAPABILITY_POWER | SYSTEM_CAPABILITY_STORAGE)
#endif

#ifndef SYSTEM_SELECTED_IMU_ACCEL_AVAILABLE
#define SYSTEM_SELECTED_IMU_ACCEL_AVAILABLE \
    JY901B_IMU_BUILD_ACCEL_AVAILABLE
#endif
#ifndef SYSTEM_SELECTED_IMU_GYRO_AVAILABLE
#define SYSTEM_SELECTED_IMU_GYRO_AVAILABLE \
    JY901B_IMU_BUILD_GYRO_AVAILABLE
#endif
#ifndef SYSTEM_SELECTED_IMU_SOFTWARE_PROPAGATION_QUALIFIED
#define SYSTEM_SELECTED_IMU_SOFTWARE_PROPAGATION_QUALIFIED \
    JY901B_IMU_BUILD_SOFTWARE_PROPAGATION_QUALIFIED
#endif
#ifndef SYSTEM_SELECTED_IMU_SOFTWARE_ALIGNMENT_QUALIFIED
#define SYSTEM_SELECTED_IMU_SOFTWARE_ALIGNMENT_QUALIFIED \
    JY901B_IMU_BUILD_SOFTWARE_ALIGNMENT_QUALIFIED
#endif
#ifndef SYSTEM_SELECTED_IMU_LANDING_STILLNESS_QUALIFIED
#define SYSTEM_SELECTED_IMU_LANDING_STILLNESS_QUALIFIED \
    JY901B_IMU_BUILD_LANDING_STILLNESS_QUALIFIED
#endif
#ifndef SYSTEM_SELECTED_IMU_LANDING_IMPACT_QUALIFIED
#define SYSTEM_SELECTED_IMU_LANDING_IMPACT_QUALIFIED \
    JY901B_IMU_BUILD_LANDING_IMPACT_QUALIFIED
#endif
#ifndef SYSTEM_SELECTED_IMU_ESTIMATOR_NOISE_RECOMMENDATION_AVAILABLE
#define SYSTEM_SELECTED_IMU_ESTIMATOR_NOISE_RECOMMENDATION_AVAILABLE \
    JY901B_IMU_BUILD_ESTIMATOR_NOISE_RECOMMENDATION_AVAILABLE
#endif
#ifndef SYSTEM_SELECTED_IMU_RECOMMENDED_PROCESS_ACCEL_E_STD_MPS2
#define SYSTEM_SELECTED_IMU_RECOMMENDED_PROCESS_ACCEL_E_STD_MPS2 \
    JY901B_IMU_RECOMMENDED_PROCESS_ACCEL_E_STD_MPS2
#endif
#ifndef SYSTEM_SELECTED_IMU_RECOMMENDED_PROCESS_ACCEL_N_STD_MPS2
#define SYSTEM_SELECTED_IMU_RECOMMENDED_PROCESS_ACCEL_N_STD_MPS2 \
    JY901B_IMU_RECOMMENDED_PROCESS_ACCEL_N_STD_MPS2
#endif
#ifndef SYSTEM_SELECTED_IMU_RECOMMENDED_PROCESS_ACCEL_U_STD_MPS2
#define SYSTEM_SELECTED_IMU_RECOMMENDED_PROCESS_ACCEL_U_STD_MPS2 \
    JY901B_IMU_RECOMMENDED_PROCESS_ACCEL_U_STD_MPS2
#endif

#ifndef SYSTEM_SELECTED_GNSS_POSITION_AVAILABLE
#define SYSTEM_SELECTED_GNSS_POSITION_AVAILABLE \
    NEO_M9N_BUILD_POSITION_AVAILABLE
#endif
#ifndef SYSTEM_SELECTED_GNSS_ESTIMATOR_NOISE_RECOMMENDATION_AVAILABLE
#define SYSTEM_SELECTED_GNSS_ESTIMATOR_NOISE_RECOMMENDATION_AVAILABLE \
    NEO_M9N_BUILD_ESTIMATOR_NOISE_RECOMMENDATION_AVAILABLE
#endif
#ifndef SYSTEM_SELECTED_GNSS_RECOMMENDED_HORIZONTAL_POSITION_STD_FLOOR_M
#define SYSTEM_SELECTED_GNSS_RECOMMENDED_HORIZONTAL_POSITION_STD_FLOOR_M \
    NEO_M9N_RECOMMENDED_HORIZONTAL_POSITION_STD_FLOOR_M
#endif
#ifndef SYSTEM_SELECTED_GNSS_RECOMMENDED_VERTICAL_POSITION_STD_FLOOR_M
#define SYSTEM_SELECTED_GNSS_RECOMMENDED_VERTICAL_POSITION_STD_FLOOR_M \
    NEO_M9N_RECOMMENDED_VERTICAL_POSITION_STD_FLOOR_M
#endif
#ifndef SYSTEM_SELECTED_GNSS_RECOMMENDED_VELOCITY_STD_FLOOR_MPS
#define SYSTEM_SELECTED_GNSS_RECOMMENDED_VELOCITY_STD_FLOOR_MPS \
    NEO_M9N_RECOMMENDED_VELOCITY_STD_FLOOR_MPS
#endif

#ifndef SYSTEM_SELECTED_MAGNETOMETER_RAW_OUTPUT_AVAILABLE
#define SYSTEM_SELECTED_MAGNETOMETER_RAW_OUTPUT_AVAILABLE \
    (SYSTEM_USER_MAGNETOMETER_ENABLE * \
     JY901B_MAGNETOMETER_BUILD_RAW_OUTPUT_AVAILABLE)
#endif
#ifndef SYSTEM_SELECTED_MAGNETOMETER_PHYSICAL_UNIT_AVAILABLE
#define SYSTEM_SELECTED_MAGNETOMETER_PHYSICAL_UNIT_AVAILABLE \
    (SYSTEM_USER_MAGNETOMETER_ENABLE * \
     JY901B_MAGNETOMETER_BUILD_PHYSICAL_UNIT_AVAILABLE)
#endif
#ifndef SYSTEM_SELECTED_MAGNETOMETER_ABSOLUTE_VECTOR_QUALIFIED
#define SYSTEM_SELECTED_MAGNETOMETER_ABSOLUTE_VECTOR_QUALIFIED \
    (SYSTEM_USER_MAGNETOMETER_ENABLE * \
     JY901B_MAGNETOMETER_BUILD_ABSOLUTE_VECTOR_QUALIFIED)
#endif

#ifndef SYSTEM_SELECTED_BAROMETER_DIRECT_ALTITUDE_AVAILABLE
#define SYSTEM_SELECTED_BAROMETER_DIRECT_ALTITUDE_AVAILABLE \
    JY901B_BAROMETER_BUILD_DIRECT_ALTITUDE_AVAILABLE
#endif
#ifndef SYSTEM_SELECTED_BAROMETER_ALIGNMENT_ORIGIN_QUALIFIED
#define SYSTEM_SELECTED_BAROMETER_ALIGNMENT_ORIGIN_QUALIFIED \
    JY901B_BAROMETER_BUILD_ALIGNMENT_ORIGIN_QUALIFIED
#endif
#ifndef SYSTEM_SELECTED_BAROMETER_LANDING_WINDOW_QUALIFIED
#define SYSTEM_SELECTED_BAROMETER_LANDING_WINDOW_QUALIFIED \
    JY901B_BAROMETER_BUILD_LANDING_WINDOW_QUALIFIED
#endif
#ifndef SYSTEM_SELECTED_BAROMETER_ESTIMATOR_NOISE_RECOMMENDATION_AVAILABLE
#define SYSTEM_SELECTED_BAROMETER_ESTIMATOR_NOISE_RECOMMENDATION_AVAILABLE \
    JY901B_BAROMETER_BUILD_ESTIMATOR_NOISE_RECOMMENDATION_AVAILABLE
#endif
#ifndef SYSTEM_SELECTED_BAROMETER_RECOMMENDED_ALTITUDE_STD_M
#define SYSTEM_SELECTED_BAROMETER_RECOMMENDED_ALTITUDE_STD_M \
    JY901B_BAROMETER_RECOMMENDED_ALTITUDE_STD_M
#endif

#ifndef SYSTEM_SELECTED_HARDWARE_QUATERNION_OUTPUT_AVAILABLE
#define SYSTEM_SELECTED_HARDWARE_QUATERNION_OUTPUT_AVAILABLE \
    JY901B_QUATERNION_BUILD_OUTPUT_AVAILABLE
#endif
#ifndef SYSTEM_SELECTED_HARDWARE_QUATERNION_PREFLIGHT_FALLBACK_QUALIFIED
#define SYSTEM_SELECTED_HARDWARE_QUATERNION_PREFLIGHT_FALLBACK_QUALIFIED \
    JY901B_QUATERNION_BUILD_PREFLIGHT_FALLBACK_QUALIFIED
#endif
#ifndef SYSTEM_SELECTED_HARDWARE_QUATERNION_PREFLIGHT_ALIGNMENT_6AXIS_QUALIFIED
#define SYSTEM_SELECTED_HARDWARE_QUATERNION_PREFLIGHT_ALIGNMENT_6AXIS_QUALIFIED \
    JY901B_QUATERNION_BUILD_PREFLIGHT_ALIGNMENT_6AXIS_QUALIFIED
#endif
#ifndef SYSTEM_SELECTED_HARDWARE_QUATERNION_PREFLIGHT_ALIGNMENT_9AXIS_QUALIFIED
#define SYSTEM_SELECTED_HARDWARE_QUATERNION_PREFLIGHT_ALIGNMENT_9AXIS_QUALIFIED \
    JY901B_QUATERNION_BUILD_PREFLIGHT_ALIGNMENT_9AXIS_QUALIFIED
#endif
#ifndef SYSTEM_SELECTED_HARDWARE_QUATERNION_AUTHORITATIVE_6AXIS_QUALIFIED
#define SYSTEM_SELECTED_HARDWARE_QUATERNION_AUTHORITATIVE_6AXIS_QUALIFIED \
    JY901B_QUATERNION_BUILD_AUTHORITATIVE_6AXIS_QUALIFIED
#endif
#ifndef SYSTEM_SELECTED_HARDWARE_QUATERNION_AUTHORITATIVE_9AXIS_QUALIFIED
#define SYSTEM_SELECTED_HARDWARE_QUATERNION_AUTHORITATIVE_9AXIS_QUALIFIED \
    JY901B_QUATERNION_BUILD_AUTHORITATIVE_9AXIS_QUALIFIED
#endif

#ifndef SYSTEM_SELECTED_MISSION_ACTION_START_AVAILABLE
#define SYSTEM_SELECTED_MISSION_ACTION_START_AVAILABLE \
    MISSION_ACTION_OUTPUT_BUILD_START_ACTION_AVAILABLE
#endif
#ifndef SYSTEM_SELECTED_MISSION_ACTION_PARACHUTE_DEPLOY_AVAILABLE
#define SYSTEM_SELECTED_MISSION_ACTION_PARACHUTE_DEPLOY_AVAILABLE \
    MISSION_ACTION_OUTPUT_BUILD_PARACHUTE_DEPLOY_AVAILABLE
#endif
#ifndef SYSTEM_SELECTED_TIME_MONOTONIC_AVAILABLE
#define SYSTEM_SELECTED_TIME_MONOTONIC_AVAILABLE                1U
#endif

/*
 * Keep selected-device recommendations distinct from explicit user
 * overrides.  Capability validation can therefore reject a selected device
 * that provides neither qualified recommendations nor a complete override.
 * The resolved VALUE macros keep selection out of the C implementation.
 */
#ifdef SYSTEM_ESTIMATOR_PROCESS_ACCEL_E_STD_MPS2_OVERRIDE
#define SYSTEM_ESTIMATOR_PROCESS_ACCEL_E_STD_MPS2_VALUE \
    SYSTEM_ESTIMATOR_PROCESS_ACCEL_E_STD_MPS2_OVERRIDE
#else
#define SYSTEM_ESTIMATOR_PROCESS_ACCEL_E_STD_MPS2_VALUE \
    SYSTEM_SELECTED_IMU_RECOMMENDED_PROCESS_ACCEL_E_STD_MPS2
#endif
#ifdef SYSTEM_ESTIMATOR_PROCESS_ACCEL_N_STD_MPS2_OVERRIDE
#define SYSTEM_ESTIMATOR_PROCESS_ACCEL_N_STD_MPS2_VALUE \
    SYSTEM_ESTIMATOR_PROCESS_ACCEL_N_STD_MPS2_OVERRIDE
#else
#define SYSTEM_ESTIMATOR_PROCESS_ACCEL_N_STD_MPS2_VALUE \
    SYSTEM_SELECTED_IMU_RECOMMENDED_PROCESS_ACCEL_N_STD_MPS2
#endif
#ifdef SYSTEM_ESTIMATOR_PROCESS_ACCEL_U_STD_MPS2_OVERRIDE
#define SYSTEM_ESTIMATOR_PROCESS_ACCEL_U_STD_MPS2_VALUE \
    SYSTEM_ESTIMATOR_PROCESS_ACCEL_U_STD_MPS2_OVERRIDE
#else
#define SYSTEM_ESTIMATOR_PROCESS_ACCEL_U_STD_MPS2_VALUE \
    SYSTEM_SELECTED_IMU_RECOMMENDED_PROCESS_ACCEL_U_STD_MPS2
#endif
#ifdef SYSTEM_ESTIMATOR_GNSS_HORIZONTAL_STD_FLOOR_M_OVERRIDE
#define SYSTEM_ESTIMATOR_GNSS_HORIZONTAL_STD_FLOOR_M_VALUE \
    SYSTEM_ESTIMATOR_GNSS_HORIZONTAL_STD_FLOOR_M_OVERRIDE
#else
#define SYSTEM_ESTIMATOR_GNSS_HORIZONTAL_STD_FLOOR_M_VALUE \
    SYSTEM_SELECTED_GNSS_RECOMMENDED_HORIZONTAL_POSITION_STD_FLOOR_M
#endif
#ifdef SYSTEM_ESTIMATOR_GNSS_VERTICAL_STD_FLOOR_M_OVERRIDE
#define SYSTEM_ESTIMATOR_GNSS_VERTICAL_STD_FLOOR_M_VALUE \
    SYSTEM_ESTIMATOR_GNSS_VERTICAL_STD_FLOOR_M_OVERRIDE
#else
#define SYSTEM_ESTIMATOR_GNSS_VERTICAL_STD_FLOOR_M_VALUE \
    SYSTEM_SELECTED_GNSS_RECOMMENDED_VERTICAL_POSITION_STD_FLOOR_M
#endif
#ifdef SYSTEM_ESTIMATOR_GNSS_VELOCITY_STD_FLOOR_MPS_OVERRIDE
#define SYSTEM_ESTIMATOR_GNSS_VELOCITY_STD_FLOOR_MPS_VALUE \
    SYSTEM_ESTIMATOR_GNSS_VELOCITY_STD_FLOOR_MPS_OVERRIDE
#else
#define SYSTEM_ESTIMATOR_GNSS_VELOCITY_STD_FLOOR_MPS_VALUE \
    SYSTEM_SELECTED_GNSS_RECOMMENDED_VELOCITY_STD_FLOOR_MPS
#endif
#ifdef SYSTEM_ESTIMATOR_BAROMETER_ALTITUDE_STD_M_OVERRIDE
#define SYSTEM_ESTIMATOR_BAROMETER_ALTITUDE_STD_M_VALUE \
    SYSTEM_ESTIMATOR_BAROMETER_ALTITUDE_STD_M_OVERRIDE
#else
#define SYSTEM_ESTIMATOR_BAROMETER_ALTITUDE_STD_M_VALUE \
    SYSTEM_SELECTED_BAROMETER_RECOMMENDED_ALTITUDE_STD_M
#endif

/* Compatibility diagnostic name retained by SSLOG0 and console output. */
#define SYSTEM_IMU_CAP_LANDING_IMPACT_DETECTION \
    SYSTEM_SELECTED_IMU_LANDING_IMPACT_QUALIFIED

_Static_assert(SYSTEM_USER_MAGNETOMETER_ENABLE ==
               JY901B_MAGNETOMETER_ADAPTER_ENABLE,
               "Target magnetometer selection and JY901B frame must match");

#endif /* __TARGET_SYSTEM_CONFIG_H */
